### ISSUE TITLE
GenerateRandomPassword function and consecutive characters

### ISSUE THREAD

**Issue by pappa75** [microsoft/MIMWAL#100]
Looks like this function generates a password that quite often will have consecutive characters. Would it be possible to enhance this function to take this into account out of the box or add possibility to allow a user to set arguments for some password requirements such as this?

**Comment by NileshGhodekar** [comment]
I believe this should not be more often than what is statistically likely from a set of 61 chars as the code is using a cryptographically strong random integer. Feel free to send a pull request if you find there may be a subtle code issue that is causing it to happen more often. For meeting any specific requirements, there is always the option of using RunPowerShellScript activity to execute a PowerShell script that returns a password that meets specific complexity requirements.

**Comment by pappa75** [comment]
Thanks for the prompt reply. We actually are currently using RunPowerShellScript activity with a PS script due to this requirement among others for our password policy.
