### ISSUE TITLE
GenerateRandomPassword Function not present

### ISSUE THREAD

**Issue by ruliane** [microsoft/MIMWAL#101]
I just installed the latest release (v2.20.0723.0) of MIMWAL, and need to use the [GenerateRandomPassword function](https://github.com/microsoft/MIMWAL/wiki/GenerateRandomPassword-Function). Sadly I can't find it:

![image](https://user-images.githubusercontent.com/5471186/113424378-5ac0d680-93d0-11eb-9e7d-102872a1bb8b.png)

**Comment by NileshGhodekar** [comment]
Hi @ruliane, MIMWAL functions are only available inside MIMWAL activities.

**Comment by ruliane** [comment]
Hi @NileshGhodekar, What do you mean by "MIMWAL activities"?
I can't find neither it in the activity picker in a workflow.:
![image](https://user-images.githubusercontent.com/5471186/114358274-04dbf380-9b73-11eb-9698-990fe88b4507.png)

... nor in the Function Evaluator activity (but this is *not* a MIMWAL activity):
![image](https://user-images.githubusercontent.com/5471186/114358861-b1b67080-9b73-11eb-9590-7d736af6cb16.png)

How am I supposed to use this function?

**Comment by mrmueller** [comment]
In your first screenshot its the ones starting with WAL:

**Comment by ruliane** [comment]
Thank you @mrmueller for your answer. So I have to generate password with the `WAL: Update Resources` activity.
