### ISSUE TITLE
Check Target exists before executing activity

### ISSUE THREAD

**Issue by FIMTooler** [microsoft/MIMWAL#102]
Have a couple of MPRs that trigger on Transition Out as well as when **any** attribute on an object is modified (last modified timestamp situation).  Thus when an object gets deleted, MPRs performing further changes are triggered.  Of course since the Target is deleted, they fail with PostProcessingError.

I did finally find that it's mentioned on the Delete Wiki that only [//Target] is remaining after a deletion.  Since the deletion activity itself was functioning correctly, it wasn't intuitive to look at that wiki to find that out.

Referencing any attribute on the Target results in the workflow crashing and the stack trace in the request saying "Permission Denied" "ResourceIsMissing".  Even if the Query or Activity Execution Condition field reference an attribute other than [//Target] failure will occur immediately as the failure seems to happen at the lookup level when it tries resolving.

I came up with this solution to prevent the Update activities (or any other WAL activity) from executing if the Target no longer exists.  It might be useful to stuff this into the wiki somewhere for others to easily find.

![image](https://user-images.githubusercontent.com/30675401/114937312-a1202780-9e0b-11eb-9acb-a95108be9c7c.png)

**Comment by NileshGhodekar** [comment]
Hi @FIMTooler, thx! Let me see what is the best place to link this.

**Comment by NileshGhodekar** [comment]
I've linked this up in the wiki's for [Activity Execution Condition](https://github.com/Microsoft/MIMWAL/wiki/Activity-Execution-Condition), [Query Resources](https://github.com/Microsoft/MIMWAL/wiki/Query-Resources) and also [Update Resources Activity](https://github.com/microsoft/MIMWAL/wiki/Update-Resources-Activity). Thanks again!
