### ISSUE TITLE
Build solution - The referenced component 'WorkflowActivityLibrary' could not be found.	WorkflowActivityLibrary.UI

### ISSUE THREAD

**Issue by thiagobeier** [microsoft/MIMWAL#106]
checked the following https://social.technet.microsoft.com/Forums/windows/en-US/0d21ed0a-4543-45e4-b6d0-79fda6c845e7/net-35-activity-library-project-in-visual-studio-2015-missing?forum=Mimwal

downloaded all dlls, sn.exe, gacutil.exe and  from mim wal github 
unlblocked all dlls, .zip file with source MIMWAL-2.20.0723.0
error building the solution

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\miminstall\Downloads\MIMWAL-2.20.0723.0\src\WorkflowActivityLibrary\bin\Release\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll' could not be found	WorkflowActivityLibrary.UI	C:\Users\miminstall\Downloads\MIMWAL-2.20.0723.0\src\WorkflowActivityLibrary.UI\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'WorkflowActivityLibrary' could not be found.	WorkflowActivityLibrary.UI			

console output

Rebuild started...
1>------ Rebuild All started: Project: WorkflowActivityLibrary.UI, Configuration: Release Any CPU ------
1>CSC : error CS0006: Metadata file 'C:\Users\miminstall\Downloads\MIMWAL-2.20.0723.0\src\WorkflowActivityLibrary\bin\Release\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll' could not be found
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by NileshGhodekar** [comment]
Are you building the solution? It should have two projects in it. If the other project which gets built first is not loading, then you probably missed to install adding support .NET 3.5 Workflow project types in you Visual Studio installation.

**Comment by NileshGhodekar** [comment]
Closing this issue as it seems the solution was to reboot the machine.
