### ISSUE TITLE
Failure adding assembly to the cache: Strong name signature could not be verified

### ISSUE THREAD

**Issue by salwaharif** [microsoft/MIMWAL#107]
I'm upgrading MIMWAL, so I reused the WAL.snk file as mentioned on the installation instructions.
But when I try to run the register command I get this :

`Failure adding assembly to the cache: Strong name signature could not be verified.  Was the assembly built
delay-signed?
Error Registering assembly in GAC:
'E:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.UI.dll'
At E:\SolutionOutput\Register.ps1:76 char:13
throw ("Error Registering assembly in GAC: $assemblyName ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Error Registeri...ibrary.UI.dll' :String) [], RuntimeException
     FullyQualifiedErrorId : Error Registering assembly in GAC: 'E:\SolutionOutput\MicrosoftServices.IdentityManageme
   nt.WorkflowActivityLibrary.UI.dll`

**Comment by salwaharif** [comment]
Found this on stackoverflow, it solved the problem : [https://stackoverflow.com/questions/24039073/can-you-install-delayed-signed-assembly-in-gac-clr-via-c-sharp-4th-edition]

**Comment by NileshGhodekar** [comment]
You should be following the Build and Deploy wiki and use sign.cmd step to sign the assembly.
