### ISSUE TITLE
With IIF statement, both true and false conditions are evaluated

### ISSUE THREAD

**Issue by FIMTooler** [Microsoft/MIMWAL#115]
When using an IIF statement, it appears that both the true and false conditions are evaluated.  Consider the simplified IIF statement below.  Both strings are the same value of 1.  Thus the True condition should convert the string "7/21/2050" to a DateTime and set the value on whatever attribute\variable the output is.

IIF(Eq("1","1"),DateTimeFromString("7/21/2050"),DateTimeFromFileTimeUTC(ConvertToNumber("9223372036854775807")))

However, this will fail because the False condition is still evaluated and throws the exception below.

Exception occurred while attempting to 'resolve' function 'System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.
DateTimeFromFileTimeUTC('9223372036854775807')

**Work around**
Use 2 activities and configure the Activity Execution Condition for each similar to below.  This allows for both the True and False conditions to be evaluated as separate activities.  With the first activity, you can update a DateTime attribute to Null() or specific date.  With the second activity, you can successfully complete the DateTimeFromFileTimeUTC() function.

1. Eq("9223372036854775807","9223372036854775807")
2. Not(Eq("9223372036854775807","9223372036854775807"))

**Comment by NileshGhodekar** [comment]
This behaviour is documented [IIF-Function](https://github.com/Microsoft/MIMWAL/wiki/IIF-Function). "Please note the IIF function evaluates the values for the second as well as the third parameter even when it only returns the value of either the second or the third parameter based on the evaluation of the condition specified as the first parameter."

Not only the potential return values, but the whole of the condition statement gets evaluated as well.  So, for example, if you have And(false, condition2:bool), condition2 will get still get parsed and evaluated even though it's going to return false.

**Comment by FIMTooler** [comment]
My apologies for not noticing that in the Remarks.  It is very unexpected from a traditional programming standpoint.
