### ISSUE TITLE
PS Credential username validation error when using UPN format

### ISSUE THREAD

**Issue by pwnstate12** [Microsoft/MIMWAL#15]
The issue is the PS Credential username format should be able to be specified using DOMAIN\USERNAME or UPN (USER@DNSDOMAIN) format.

**Comment by NileshGhodekar** [comment]
Hi, can you please explain your scenario where you cannot use DOMAIN\USERNAME format and MUST use the UPN format?

**Comment by pwnstate12** [comment]
Hi Nilesh,

Basically, I would like to use a MIM WAL powershell activity to make updates in a SaaS app that requires an authN request to be completed when creating a remote powershell session.  To complete the login request the userID needs to be in upn/email format.

The PScredential object does not require the use of the domain/username format so I am currently creating my own PScredential directly in the script that i am running in my powershell activity, but that is not a good security practice in my opinion so it would be great if I could use the built-in MIM WAL PScredential feature.  Thanks for the follow-up please let me know if the upn format will be made available for the PScredential feature in the future.

Sent from my Windows Phone
________________________________

**Comment by NileshGhodekar** [comment]
Yes, this is the usecase that came to my mind after I posted the earlier reply. We can get this support in the next release.

**Comment by NileshGhodekar** [comment]
Hi, This change has made its way in v2.16.0710.0. Please test if you can. I'll close this issue now.
