### ISSUE TITLE
LDAP filter check works only for the samAccountName attribute. 

### ISSUE THREAD

**Issue by guyhorn1964** [Microsoft/MIMWAL#16]
I tried to check mailNickname and userPrincipal name. The MIMWAL just ignores the mailNickname. The userPrincipalName is causing an error: "The expression 'Objectclass=user)(ObjectCategory=Person)(userprincipalname='Jeroen.Bos@demo.lan'' is invalid."

The LDP filter works fine with Get-AdUser.

**Comment by EugeneSergeev** [comment]
I would try without quotes

**Comment by NileshGhodekar** [comment]
I'm closing this issue as you just need to fix your LDAP filter. You can find a sample in the activity Wiki. ...And additional samples on how to write a LDAP filter on TechNet / MSDN.
