### ISSUE TITLE
import-module activedirectory fails

### ISSUE THREAD

**Issue by guyhorn1964** [Microsoft/MIMWAL#17]
Hi,
While using the powershell activity, when importing explicitly or just using get-aduser this event is thrown:

WAL (2.16.0320.0): 06/14/2016 12:57:12.9461: <>c : <SetupStreamEventHandlers>b__68_0: The 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\activedirectory\activedirectory.psd1' module cannot be imported because its manifest contains one or more members that are not valid. The valid manifest members are ('ModuleToProcess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVersion', 'PowerShellHostName', 'PowerShellHostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'RequiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'FunctionsToExport', 'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the members that are not valid ('HelpInfoUri'), then try to import the module again.

At line:139 char:22
+         Import-Module <<<<  activedirectory

**Comment by NileshGhodekar** [comment]
You can't directly use any modules that are a higher version than PowerShell 2.0. This has been adequately discussed in the Run PowerShell Script activity wiki. Will now close this issue.
