### ISSUE TITLE
Unique values from RandomNumber

### ISSUE THREAD

**Issue by plassander** [Microsoft/MIMWAL#21]
It is a high chance/risk that the function RandomNumber will return the same value if it runs several times in a row in a workflow, and also if it runs at about the same time in different treads. 
It would be nice if a seed was used when the class is instantiated (maybe based on thread id), and also using the same Random object within a tread if it is possible, and not recreating it for each function call.
[https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx#ThreadSafety](url)
Cheers

**Comment by NileshGhodekar** [comment]
The default seed it time-based (Ticks) which is as much more precise that a thread id.  Random is a pseudo random number generator.  What is the use case that for it needs to be precise? If this is for generating passwords, then GeneratePassword function uses cryptographically strong random number generator.

**Comment by plassander** [comment]
Hi Nilesh,
We are not using it for password. 
From documentation at MSDN: “If the same seed is used for separate Random objects, they will generate the same series of random numbers.” And “…parameterless Random() constructor uses the system clock to generate its seed value. However, because the clock has finite resolution, using the parameterless constructor to create different Random objects in close succession creates random number generators that produce identical sequences of random numbers.”. Note that you need to copy-paste the link above. 

Result from test example: 416,739,163,**914,914**,338,191,514,**836,836**

![random](https://cloud.githubusercontent.com/assets/16652755/20393744/49189f78-acdd-11e6-8152-74e1cda90d94.png)
Cheers,
Patrik

**Comment by NileshGhodekar** [comment]
Hi Patrik, I understand it's a pseudo random number generate and will generate the same number for the same Ticks and hence chances are you'll get the same number if you use it in the same activity, but my question was why do you need to generate multiple random numbers in the same activity and still need them to be unique? One alternative, taking your example is to generate first Random Number between 100 and 199, Second from 200 to 299 and so on... That will guarantee that they'll be different from each other.

**Comment by Amethi** [comment]
Random != Unique! If you want unique, you'll have to iterate until you have the prerequisite unique values.

**Comment by NileshGhodekar** [comment]
Rightly summarized Jay! Random does not guarantee uniqueness.  RandomNumber between 1 and 10 will generate same numbers very quickly. Like I mentioned, if you want uniqueness within an activity you need to specify non-overlapping min and max bounds. There can be no guarantee the number will be unique across activities even though "seed" will be very very very unlikely to be the same.

**Comment by plassander** [comment]
Yes, I agree on basically everything you say. But that was not my point. RandomNumber would be a more “efficient” if Random was instantiated only once during the life-cycle of an activity.

Thanks  :-)
