### ISSUE TITLE
Target Lookup on Delete Resources Activity gets PostProcessingError

### ISSUE THREAD

**Issue by mbalashov** [Microsoft/MIMWAL#22]
Hi All,

I have tried to use Delete Resources Activity to update linked resources (not by explicit reference, but logically linked by some attributes). So I used Target Lookup to get a DisplayName of deleting Resource and got PostPrecessingError during Activity execution. After I had tried to lookup different attributes of deleted resources and use it in Notification message to see values and I got very interesting results:
- [//Target] returns an ObjectID of deleted resource;
- [//Target/ObjectID] returns nothing;
- [//Target/DisplayName] returns nothing;
- etc, all other attributes of target returns nothing :(

I found workaround using of DisplayName of Request - this attribute contains information about deleted Resource and it is possible to get this information by simple text operations.

Maybe it is significant: Resources that I tried to delete was a custom resources.

**Comment by NileshGhodekar** [comment]
After the delete request is committed (i.e. in Action workflow), you don't have access to any information on the object. I would have expected [//Target] and [//Target/ObjectID] to return same info, but you seems to be saying it does not, so it may be a bug. All other is expected and nothing to do with it being a custom resource.

**Comment by weyto** [comment]
You can do this in an Action workflow with [//Request/Target].
But note:
The referenced Objects must have a string attribute with the ObjectID of the Deleted Object.

**Comment by mbalashov** [comment]
**NileshGhodekar:** > After the delete request is committed (i.e. in Action workflow), you don't have access to any information on the object.

If I have correctly understood article [Delete-Resources-Activity](https://github.com/Microsoft/MIMWAL/wiki/Delete-Resources-Activity) is possible to use Target Lookup of deleting object to get some attribute values.

**weyto** > But note:
The referenced Objects must have a string attribute with the ObjectID of the Deleted Object.

Yes, I have understood that it is possible when I use "direct" links by ObjectID

**Comment by NileshGhodekar** [comment]
@mbalashov, the wiki examples call out where AuthZ workflows are needed which is before the resource is actually deleted. Post AuthZ, you have no traces of the object (except in FIM Reporting tables). However, I can see that it's a good idea to update the Wiki to call it out explicitly. Thanks!

**Comment by NileshGhodekar** [comment]
Closing this issue. I've updated the Implementation Guidance section to bring some more clarity on this topic.
