### ISSUE TITLE
Powershell workflow - returns "The -file parameter does not exist."

### ISSUE THREAD

**Issue by shackdan** [Microsoft/MIMWAL#23]
I'm calling a PowerShell 3.0 script to workaround some limitations of 2.0
The workflow runs (and the script runs fine) but still results in an Error (Event ID 40403) -see content below.

WAL (2.16.0710.0): 12/03/2016 10:21:01.6126: <>c : <SetupStreamEventHandlers>b__68_0: The argument 'c:\set-rds.v3.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

At line:11 char:15
+ powershell.exe <<<<  -version 3.0 -File $script -AccountName $AccountName -domain $domain

**Comment by NileshGhodekar** [comment]
The error is what is sent by the PowerShell engine.  You may be looking at the old message if your rds script is running or the script is not erroring out as reported by the PowerShell engine. Try running powershell.exe -version 3.0 -File $script -AccountName $AccountName -domain $domain manually.

**Comment by shackdan** [comment]
Running manually works fine:
PS C:\WINDOWS\system32> $psversiontable.psversion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1


PS C:\WINDOWS\system32> powershell -version 3 -file c:\dev\set-rds.v3.ps1 -AccountName uset011 -domain thenewtonlab
RDS-Set

**Comment by NileshGhodekar** [comment]
The workflow is trying to run the file from c:\set-rds.v3.ps1 not from c:\dev.

**Comment by shackdan** [comment]
UGH...well now I feel foolish...sorry for the bother.
and great work on this awesome too.
D

**Comment by NileshGhodekar** [comment]
Sometimes you need additional pair of eyes :) BTW, for production, I'm hoping you plan to use inline script as depicted in the Wiki examples. Closing the issue now.
