### ISSUE TITLE
Wiki update Build and Deploy

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMWAL#24]
It might be nice to update the https://github.com/Microsoft/MIMWAL/wiki/build-and-deployment page to tell the newbies where to find the dlls that they need to copy.
Go to server with FIM Service Installed
Go to c:\Windows\Assembly\ to find
Microsoft.IdentityManagement.WebUI.Controls.dll
Microsoft.IdentityManagement.WFExtensionInterfaces.dll
Go to Program Files\Microsoft Forefront Identity Manager\2010\Service to find
Microsoft.ResourceManagement.dll
Microsoft.ResourceManagement.WorkflowContract.dll

**Comment by NileshGhodekar** [comment]
@DLundell, thanks for the feedback. There is a note in the wiki (For time saving tips on how to gather these files and any other common compilations issues, please take a look the [MIMWAL Project TechNet forum](https://social.technet.microsoft.com/Forums/en-US/35860b8c-0c36-4cd2-832e-9b16e72ecc9e/dll-extraction?forum=Mimwal) thread) that takes to the detailed instructions. But probably we can just link the binary names to there path in the GitHub source code commit history before they were deleted from the source code at the time the repo became public.

**Comment by NileshGhodekar** [comment]
I'm closing this issue. I've updated the wiki with links (and also the accompanying note that "These files are **neither included nor distributed** as part of the MIMWAL project source code or release downloads (as their distribution and usage is governed by the licensing agreement of the respective products they are shipped with)..."
