### ISSUE TITLE
Update Resource Activity: Request Operation for Multivalue Attribut

### ISSUE THREAD

**Issue by weyto** [Microsoft/MIMWAL#25]
Hi everybody,

for a couple of weeks we struggling over a little problem with the Update Resource Activity.
In the Activity was a value expression like [//Target/ReferenceAttribut/MultiValueAttribute] and in the Target Expression [//Target/MultiValueAttribut] with the option Allow Null.
So we want to copy the Values of a MultiValueAttribut from one object to an other object.
If we look at the generated Requests we see, that the Attribut was updated with the Operation Type Modify instead of Add and Remove.
So the problem was, that based on this requests that subprocess (R-MPR) wasn't triggered.
Why? The MPR is configured for Add and Remove only on the Target Attribut (because it is a multivalue attribut).
So when we modify the R-MPR to Operation Type Modify, everything works well, but in the RCDC of the MPR is the following error message visible:
Policy mis-configuration: Your selection of Modify operation requires specification of single-valued attributes.

If you use the WAL-Function InsertValues or RemoveValues the OperationType of the Request will be ok (like Add or Remove).
But in our case we can't use the InsertValues or RemoveValues, because we want a complete copy of this attribut and have no updates on the value of the Source Attribut itself.

**Comment by NileshGhodekar** [comment]
WAL does not do schema validation, so it's up to the WF designer to call correct functions. I'm not sure why you can't call InsertValues (or RemoveValues) function. They don't change the input parameter. You could probably just delete the values (Null() function with Allow Null) in first activity and then InsertValues(sourceAttribute) in a subsequent activity. You could also try RemoveValues(targetAttribute) and InsertValues(sourceAttribute).

**Comment by NileshGhodekar** [comment]
I'm closing this issue as resolved.
