### ISSUE TITLE
Register.ps1 does not support split-server installation

### ISSUE THREAD

**Issue by ekrotki** [Microsoft/MIMWAL#27]
Hello,
I just tried installing MIMWAL on MIM installed separately - portal in machine A, MIMService on machine B.
Started from MIMService on machine B and installation went successfully posting error regarding not installed portal. OK so far.
Went to Portal machine A where register.ps1 failed attempting loading FIMAutomation. (WHY?) 
Added one, ran again, pile of errors appeared, but MIMWAL looks to get installed correctly :)
I feel that some ordering of operation within the script and loading FIMAutomation only if really needed may help to get clean install on both machines.

**Comment by NileshGhodekar** [comment]
Feel free to fix the script and send a pull request. Within Microsoft, we don't recommend splitting the servers, so don't have the split setup to test changes.

**Comment by Amethi** [comment]
I did wonder if anyone choose to use this topology. I never saw any benefit personally.

**Comment by ekrotki** [comment]
I will try to fix the script as soon as I will have some free cycles.
Benefits appear as soon as organization may cross 200k users or more, but any discussion of this matter is out of topic. Regarding recommended topologies, please refer to the article: https://github.com/Microsoft/MIMWAL/issues/27#issuecomment-278391383

**Comment by NileshGhodekar** [comment]
Agree to keep the discussion of topology out of topic :) But for now, I'm closing this issue with the comment that the contribution to make the script work for dedicated portal server topology will be accepted.

**Comment by guyhorn1964** [comment]
MIMWAL is a great piece of software. While installing it I encountered some imperfections. So let’s make things better.

First of all the installation script ‘register.ps1’ is only suitable if your server has two roles installed: Portal and FIMService. As Microsoft itself advises not to do that in s large environment that’s obviously not the way to go. If you try you will get in both servers annoying errors that can be ignored. But I don’t like my scream bleeding red. So I adjusted the installation script. Actually I created two scripts that can be run separately
error-free. You can find the modified scripts here.

 Then I also had some problems with the
dll’s. Now that’s the first time I have problems with that but the solution is
worth documenting it.            

The error:

PS
C:\SolutionOutput> .\Register.ps1 -PortalSiteName “MIM Portal”

DEBUG:
Registering assembly in GAC:
‘C:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll’

DEBUG:
Microsoft (R) .NET Global Assembly Cache Utility.  Version 3.5.21022.8

Copyright
(c) Microsoft Corporation.  All rights reserved.

 

Failure
adding assembly to the cache: Strong name signature could not be verified.  Was
the assembly built delay-signed?

 

Error
Registering assembly in GAC:
‘C:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll’

At
C:\SolutionOutput\Register.ps1:76 char:13

+
throw (“Error Registering assembly in GAC: ‘$assemblyName …

+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    +
CategoryInfo          : OperationStopped: (Error Registeri…tyLibrary.dll’
:String) [], RuntimeException

    +
FullyQualifiedErrorId : Error Registering assembly in GAC:
‘C:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll’

 The solution:

Place the files somewhere. E.G. in C:\SolutionOutput.

 Set-Location C:\SolutionOutput

$dlls = Get-ChildItem -Filter ‘*dll’

$dlls.name

foreach ($item in $dlls)

{

    .\SN -Vr $item.name

}

Set-Location .\dlls

$dlls = Get-ChildItem -Filter ‘*dll’

$dlls.name

foreach ($item in $dlls)

{

    .\SN -Vr $item.name

}
