### ISSUE TITLE
updating from fimwal2 to mimwal

### ISSUE THREAD

**Issue by Eabikhers** [Microsoft/MIMWAL#29]
hello , any help in the update from fimwal2 to mimwal!!
also im nt finding the folder of fimwal2 on the server although fimwal is installed

**Comment by NileshGhodekar** [comment]
Have you checked the FAQ https://github.com/Microsoft/MIMWAL/wiki/FAQ#how-do-i-migrate-from-fimwal-2? What in particular you are looking at? Follow the steps in B&D wiki and it will be automatically upgraded.

**Comment by NileshGhodekar** [comment]
I'll close this issue for now. And in case you also don't have the snk key, please check the TechNet thread: [Missing .snk file form previous install](https://social.technet.microsoft.com/Forums/en-US/69c2c48f-7f2f-43aa-8f00-65ce076ec56c/missing-snk-file-form-previous-install?forum=Mimwal)
