### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Amethi** [Microsoft/MIMWAL#3]
Hey guys,  I'm creating some unit tests to maximise confidence in the solution. I'm concentrating on the evaluated functions at the moment ([ExpressionFunction.cs](https://github.com/Microsoft/MIMWAL/blob/master/src/WorkflowActivityLibrary/Common/ExpressionFunction.cs)) I suspect it'll take a bit of work to do properly so if this isn't likely to be appreciated let me know.

I'm creating a test project with files for each class being tested. I can do a small pull request with just a couple of unit tests in for a quick check or the whole class as a stopping point, whatever's preferable.

**Comment by NileshGhodekar** [comment]
Hi Jay, thanks! Yes, there is a definite need for automated tests, but it is not getting prioritised for one reason or another, the biggest being automated tests for FIM WF’s are too big a task and the other being that WAL had already been used in a large number of customer environments. When we were migrating from FIMWAL “1” to FIMWAL “2” which was a major revamp (compared to in the context of this discussion MIMWAL is just a branding change to FIMWAL “2” and nothing more),  Vibha Soi, one of our colleagues started work on the automated unit tests for WAL functions. She did some initial work on the unit tests based on the external xml input file, so any functions could be tested by entering / updating test data in the xml. I still have the source code if anyone want to pursue it further. However, given that any regression to changes to the functions is highly localised, we did not take it any further. The biggest bang for buck will be if we can execute these test cases in an automated way in the FIM WF runtime. This would cover risk of regression in the WAL lookup resolution processing itself. If you have anything on how WAL activities can be tested in an automated fashion, I can check-in the prior work on unit tests for WAL functions as the starting point.

**Comment by Amethi** [comment]
Thanks Nilesh, from that I understand that full integration testing is preferred, i.e. test the execution of the workflows themselves which in turn tests the internals, like these functions. I'll have to give it some thought :)

**Comment by NileshGhodekar** [comment]
In my opinion we need to prioratise where the biggest bang for our buck is. If we change the behaviour of a function, the regression in is localized, easy to spot and fixed. Changes in an activity / lookup resolution needs lot of testing for regression. So in my opinion we prioratise that and look for a way forward for that. Once plan / prototype for that is in place, we then start full blown with this low hanging fruit first.

**Comment by NileshGhodekar** [comment]
Guys, I'll be closing this Issue for now. Unless we have a plan forward with unit testing activities themselves or integrated workflow testing, I don't see this getting much further.
