### ISSUE TITLE
Request stuck  in PostProcessing status

### ISSUE THREAD

**Issue by Ivars-Z** [Microsoft/MIMWAL#30]
Hello, i have action workflow that contains "Add Delay" activity,
when [//WorkflowData/Value] is used in "Timeout Duration" field, all workflow activities are executed but main request stays in PostProcessing status.

Main request ends with "Completed" status if string value (for example "00:00:30") instead of [//WorkflowData/Value] is used.

**Comment by NileshGhodekar** [comment]
Is Delay activity is the last activity in the workflow? Then it's unlikely to have anything to do with how you pass the value, but likely with the value in the WF data itself. You should confirm the value in WF data.

**Comment by Ivars-Z** [comment]
Delay activity is 2nd activity(wokflow jas 5 activities in total), in 1st activity delay time is calculated, all workflow is working as expected, calculated delay is ocuring but the main request stays in PostProcesing status. Verified that the same behavior is ocuring when in 1st activity just plain string value is assigned to [//WorkflowData/Value] that is used in Timeout Duration in Delay activity.

**Comment by NileshGhodekar** [comment]
I quickly tested this on my FIM box and I don't see this issue. I'd three simple activities, first one UpdateResources to set the delay value in WF data variable,  second Add Delay that uses that WF data value and 3rd UpdateReosources to update the Target's description with that value. I see no issues.
If the Delay is over and it's proceeding with the next activity in the workflow, then it will not be a WAL issue. You may have to raise a support call for the FIM product, if you can't figure out.

**Comment by Ivars-Z** [comment]
I did some aditional testing, specifying delay value directly in delay activity,
My findings when diferent values are specified:
"00:00:30" - all request statuses is completed including main request
"00:01:30" - main request status stays in PostProcessing all other requests are completed
"00:02:00" - main request status stays in PostProcessing all other requests are completed

**Comment by NileshGhodekar** [comment]
I don't see this even with 30 minutes of delay and the main request finishes in a couple of minutes after the delay is expired. Anyway the best way forward is probably to raise a call for the FIM product. I'll close this issue for now as there isn't much we can do here to help.
