### ISSUE TITLE
Can't fork the wiki

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMWAL#31]
I spotted a few errors in the wiki (simple minor stuff) and want to fix it but when I fork the repository it is just the code. The guidelines for contributing say to fork the MIM WAL wiki repo. But when I go to the link https://github.com/Microsoft/MIMWAL/wiki and then click fork, I just get the same result code but no wiki.

**Comment by NileshGhodekar** [comment]
@DLundell, are you not able to clone with wiki using the "Clone this wiki" link under the right hand sidebar, make the changes and push the changes? Are you getting any access denied error?

**Comment by NileshGhodekar** [comment]
Thanks to @Amethi, I now have confirmation that you can clone the wiki, but cannot submit a push any changes. He also pointed me to the URL: http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html, which show this is not quite straight forward. Hence, I've just updated the Contributing.md to reflect this as only options seems to be submitting an issue. I'll now close this issue. Thanks!
