### ISSUE TITLE
Lookups page an incorrect example

### ISSUE THREAD

**Issue by DLundell** [Microsoft/MIMWAL#32]
https://github.com/Microsoft/MIMWAL/wiki/Lookups references CreatedDate. The correct name of the attribute is CreatedTime 
https://msdn.microsoft.com/en-us/library/windows/desktop/ee652451(v=vs.100).aspx

Here is a bit from the page:
Examples
• [//Request] 
• [//Request/CreatedDate]

**Comment by JefTek** [comment]
Thanks Dave for reviewing and identifying this error.  I corrected the wiki entry and published the update!
