### ISSUE TITLE
DateTimeFromFileTimeUTC usage

### ISSUE THREAD

**Issue by xrobert5** [Microsoft/MIMWAL#33]
I am using the DateTimeFromFileTimeUTC function to get the AD attribute PWD Last Set into the portal and I did something like:
[//WorkflowData/ADPWLastSet]   <----   DateTimeFromFileTimeUTC([//Target/LongADPWLastSet]) 	
[//Target/ADPWLastSet] <----  [//WorkflowData/ADPWLastSet] 

Where LongADPWLastSet is defined as an integer and is CORRECTLY valued in the Portal but I get the below error when publishing the time to ADPWLastSet; ASPWLastSet is defined as a DateTime attribute.
Has anyone used that function successfully? Any idea what I am doing wrong???

Exception occurred while attempting to 'resolve' function 'System.ArgumentOutOfRangeException: Not a valid Win32 FileTime. Parameter name: fileTime at System.DateTime.FromFileTimeUtc(Int64 fileTime) at MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Common.ExpressionFunction.DateTimeFromFileTimeUtc() at MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Common.ExpressionFunction.Run()': 'DateTimeFromFileTimeUTC'

**Comment by NileshGhodekar** [comment]
How are you verifying it's CORRECTLY valued? Please share the WAL event log entry in the verbose mode that will show the actual value that is being passed to the function.

**Comment by xrobert5** [comment]
The verbose view from event log (did not show the value being passed ..)

WAL (2.16.1028.0): 04/01/2017 09:28:30.8228: ExpressionFunction : Run: Exception in 'ExpressionFunction : Run'. Details: MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Exceptions.InvalidFunctionOperationException: Exception occurred while attempting to 'resolve' function 'System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.
Parameter name: fileTime
   at System.DateTime.FromFileTimeUtc(Int64 fileTime)
   at MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Common.ExpressionFunction.DateTimeFromFileTimeUtc()
   at MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Common.ExpressionFunction.Run()': 'DateTimeFromFileTimeUTC'..
Extended Properties:
WorkflowInstanceId: 96486024-3f63-41e2-a15a-863d2da2c4cd
TargetId: 83ab0e83-9ca5-4760-8a0e-82204b4bab46
RequestId: f0a7af2c-4834-420b-a8f0-9d6c20d77b96
WorkflowDefinitionId: 85b4ed6a-ebaa-473a-8227-0620d43621b6
ActorId: e05d1f1b-3d5e-4014-baa6-94dee7d68c89

Here is the value straight from AD that makes it to the Portal: 131326331121208114
And using a utility it gives: 2/26/2017, 7:38:32 PM

**Comment by NileshGhodekar** [comment]
you can check the value for LongADPWLastSet in the logs OR search for 131326331121208114 in the logs OR you can hard-code the value in DateTimeFromFileTimeUTC. I get that exception for a negative value only.

**Comment by xrobert5** [comment]
Plugging 131326331121208114 in DateTime.FromFileTimeUtc did not do and produced the same error stating that this is not a valid file time!!  The wiki gives DateTimeFromFileTimeUTC([//Target/AccountExpires]) as example and I am assuming that the value of [//Target/AccountExpires] could for instance be 131326331121208114.  I may resolve to coding then :)

**Comment by NileshGhodekar** [comment]
That is strange! This hardcoded or any other value work on my server (and obviously for lot many other folks). WAL (2.17.0323.0): 04/03/2017 05:41:54.9852: ExpressionFunction : DateTimeFromFileTimeUtc: DateTimeFromFileTimeUtc('131326331121208114') returned '02/27/2017 01:38:32'.
Here is the one liner PowerShell equivalent of relevant WAL C# code for 131326331121208114: [DateTime]::FromFileTimeUtc([Convert]::ToInt64(131326331121208114)).  The error you are receiving is originating in .NET framework API, so it's likely that you need to look beyond coding for resolving this issue, but do tell us if you find a resolution.

**Comment by xrobert5** [comment]
I restarted all the FIM Service boxes and then all of a sudden, the function worked!! I am glad it works but still puzzled!! :)
