### ISSUE TITLE
Escape XPath function request

### ISSUE THREAD

**Issue by trimolen** [Microsoft/MIMWAL#35]
When performing a search, for example a query in a Update Resource s activity I would like a new function that ‘escapes’ the XPath query.

For example I have a query: [/Department[DisplayName=’[//Target/Department]’]

If the department has a single quote in its name then nothing is returned (but I don’t see an error), but the following query would work (changing the type of quote): [/Department[DisplayName=”[//Target/Department]”]

And vice-versa if the department contained a double-quote.

(I don’t know what you need to do if the value contains both a single and double quote.)

**Comment by NileshGhodekar** [comment]
I'd previously looked at this briefly and had concluded that this is best left with the designer as after a brief review I'd not found a reliable way to do this in WAL and no-one was really asking for it, so ROI did not warrant further investigation. Like you noticed given the nature of XPath queries that are formed  most likely you'll be able to get away with it using design time syntax.  Also WAL supports function expressions for XPath, so one could use simple ReplaceString functions if they foresee such need. If you can provide some real examples of data that will fail XPath after simple trick or where ReplaceString will not be enough, I'll investigate again how this can be made better. I'll close this issue for now, but continue to use this thread for further discussion.
