### ISSUE TITLE
Create Synchronous Workflows

### ISSUE THREAD

**Issue by mawadallah** [Microsoft/MIMWAL#36]
need to support to run two synchronous workflows or sequential ones.

**Comment by NileshGhodekar** [comment]
The correct way to do this will be via authoring correct policy (MPRs) and de-normalisation of workflows (combine these workflows in a single AuthZ and AuthN workflows). The conditional execution in WAL activities can also help to trigger (or not trigger) the relevant workflows. There is no plan to implement such capability directly in WAL as the MIM product architecture does not support it and there are other supported design options I mentioned earlier. I'll close this issue now.
