### ISSUE TITLE
Update RCDC ConfigurationData

### ISSUE THREAD

**Issue by wim-beck** [Microsoft/MIMWAL#37]
I have a use case where I need to create a new attribute dynamically. So I started out by creating an attribute and a binding via a create resources WAL activity. So far so good. 

Now I would like to add this new attribute to the rcdc. I have already a function to manipulate an existing configuration data object and insert an xml element (see https://github.com/wim-beck/is4u-fim-powershell/wiki/Add-ElementToRcdc), but I cannot find a way to do this (in a simple way) with a powershell activity. 
The way I would like to do this, is via a combination of a powershell script (local to the activity) manipulating the configuration data and an update resources activity to upload the data to the rcdc object.

Is running an external script my only option here?

**Comment by NileshGhodekar** [comment]
Not sure how this will work in a prod environment as this will also involve restarting  FIMSerivce / IIS on servers not executing the request as well post updates, but If you can do this via an external script, you should be able to run the script using RunPowerShellScript activity. If you are using FIMAutomation snap-in, then there is a know issue with FIMAutomation snap-in that requires edits to RM.exe.config to qualify the base address with port.

**Comment by NileshGhodekar** [comment]
I'm closing this issue. Let me know if you need any additional help or have any suggestions.
