### ISSUE TITLE
Eq compareCase parameter default value?

### ISSUE THREAD

**Issue by Amethi** [Microsoft/MIMWAL#38]
In the Eq function, I'm assuming that the compareCase parameter has a default value of False? It might be good to state this in the documentation.

https://github.com/Microsoft/MIMWAL/wiki/Eq-Function

**Comment by NileshGhodekar** [comment]
I think you can solve the puzzle correctly :) Hint: The parameter is called compareCase and it is optional. What would be the default value if it was called ignoreCase? :)
Anyways the wiki now removed the puzzle. Thanks! Will close.
