### ISSUE TITLE
Convert String to DateTime

### ISSUE THREAD

**Issue by iorek0** [Microsoft/MIMWAL#39]
I've noticed that it's possible to convert a datetime to its string value but not the other way around.
I'm trying to fill an attribute with a default date (epoche time) so i can compare it later with a recent one.

Thanks

**Comment by NileshGhodekar** [comment]
We'll look at adding this function in a future release of WAL, but for now, you can use DateTimeFromFileTimeUtc() by feeding it the equivalent number value. 

PS: You can get the number by running a small PowerShell script such as (Get-Date "1/1/9999").ToFileTimeUtc() and then use this number in your workflow configuration.

**Comment by NileshGhodekar** [comment]
The latest release [MIMWAL v2.17.0721.0](https://github.com/Microsoft/MIMWAL/releases/tag/v2.17.0721.0) now has the function [DateTimeFromString](https://github.com/Microsoft/MIMWAL/wiki/DateTimeFromString-Function).
