### ISSUE TITLE
Iteration support for WAL email activities

### ISSUE THREAD

**Issue by 2xTsei** [Microsoft/MIMWAL#40]
Referencing to this thread:
https://social.technet.microsoft.com/Forums/en-US/708bd498-2085-4503-9f02-88cea2464303/mimwal-send-individual-mail-for-every-member-added-to-a-group?forum=Mimwal

Little bit more detailed info:

So we have a case where we want to send email for a user added to a security group. The email should contain user specifig info about the user itself for example like a username. Also there might be a need for send that email for example an manager or some other person but not the user added to the group.

All those things could be done currently when we are adding one user. But when we are adding more than one user, it is inpossible to send an individual email with any personal info.

**Comment by NileshGhodekar** [comment]
Hi @2xTsei, can you please try building the code from my fork https://github.com/NileshGhodekar/MIMWAL/archive/master.zip and let me know if it works for your need so that I can promote this as a new public release?

**Comment by 2xTsei** [comment]
Hi

Just to be sure. I compile this and install it like the previous mimwal version? So there is no need to remove the another version before or something?

BR
Joonas aka. 2xTsei

**Comment by 2xTsei** [comment]
No problems with updating the mimwal. Now I am trying to get the workflow solution to work ☺!

BR
Joonas

From: Jokinen, Joonas
Sent: 11. heinäkuuta 2017 9:17
To: 'Microsoft/MIMWAL' <reply@reply.github.com>; Microsoft/MIMWAL <MIMWAL@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/MIMWAL] Iteration support for WAL email activities (#40)

Hi

Just to be sure. I compile this and install it like the previous mimwal version? So there is no need to remove the another version before or something?

BR
Joonas aka. 2xTsei

**Comment by NileshGhodekar** [comment]
Yes, there are no separate B&D instructions apart from already provided in the Wiki. While the activity is fully functional as it stands, I'm toying with the idea to change the order of Queries / Iteration support. Right now, as is the case will existing activities,. you can use Query Lookup expressions to define an Iteration. However, it probably makes more sense here to be able to define Queries inside the Iteration loop. But this is a big structural change. So let's see. Right now, you can get the additional info to put in the email via Value expressions only such as [//Value/AccountName] => [//WorkflowData/AccountName] and so on.
Secondly, there is a minor bug that if you don't open, edit and save your any *existing* SendEmailNotification activity UI, there will a runtime error about corrupt definitions table. I'll check in the fix for this shortly.

**Comment by 2xTsei** [comment]
Yep, I got it working!

Now we are thinking to move this into a production. Can you say when you can publish a new version of MIMWAL with this feature and the bug fixed?

BR
Joonas

**Comment by NileshGhodekar** [comment]
It will probably be at least week away.

**Comment by NileshGhodekar** [comment]
Hi, I just checked in finalised code. Now you can define queries using iteration values. Can you please test and confirm your use case still works fine? Once you confirm, we'll be a step closer to the final public release.

Probably in future release, we'll adopt this capability of being able to define queries using iteration values across the remaining activities.

**Comment by 2xTsei** [comment]
Hi



Can you point direct link for the finalised code. Thanks.



Br

Joonas

________________________________
Lähettäjä: Nilesh Ghodekar [notifications@github.com]
Lähetetty: 13. heinäkuuta 2017 1:21
Vastaanottaja: Microsoft/MIMWAL
Kopio: Jokinen, Joonas; Mention
Aihe: Re: [Microsoft/MIMWAL] Iteration support for WAL email activities (#40)


Hi, I just checked in finalised code. Now you can define queries using iteration values. Can you please test and confirm your use case still works fine? Once you confirm, we'll be a step closer to the final public release.

Probably in future release, we'll adopt this capability of being able to define queries using iteration values across the remaining activities.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Microsoft_MIMWAL_issues_40-23issuecomment-2D314914452&d=DwMFaQ&c=vgc7_vOYmgImobMVdyKsCY1rdGZhhtCa2JetijQZAG0&r=x0nuG-rnw5ZA4o6EKPnLRF5aq7isLObuxXbQfX7jEw8&m=JCWzGdJEuFoC5puj0EYPwjmto32x05qi7eqx5TmsFck&s=C4zRdW1ZeUmp2ETMx5We4IxLJf5Lfip2bXKyGLynAsg&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AciC4-5FS3dNyrR8h5x4uI-5F0mdQPMuPttfks5sNUbZgaJpZM4OOLAS&d=DwMFaQ&c=vgc7_vOYmgImobMVdyKsCY1rdGZhhtCa2JetijQZAG0&r=x0nuG-rnw5ZA4o6EKPnLRF5aq7isLObuxXbQfX7jEw8&m=JCWzGdJEuFoC5puj0EYPwjmto32x05qi7eqx5TmsFck&s=8uOF_cPL7YsNUXuvyaJryKfYUV1RoWmCTn18gavwMvQ&e=>.

**********************************************************************
The information in this e-mail (and any attachments) is intended exclusively for the addressee(s). Any use by a party other than the addressee(s) is prohibited. The information may be confidential in nature and fall under a duty of non-disclosure. If you are not the addressee, please notify the sender and delete this e-mail. KPMG cannot guarantee that e-mail communications are secure or error-free, as information could be intercepted, corrupted, amended, lost, destroyed, arrive late or incomplete, or contain viruses. Any opinions or advice contained in this e-mail are subject to the terms and conditions expressed in the governing KPMG client engagement letter. Please consider the environment before printing this email.

**Comment by NileshGhodekar** [comment]
Same place you downloaded last time. In my fork.

**Comment by 2xTsei** [comment]
Hi



I downloaded it again from the same link what you already provided. I updated MIMWAL and tested the usecase and everything work as expected!



BR

Joonas



________________________________
Lähettäjä: Nilesh Ghodekar [notifications@github.com]
Lähetetty: 18. heinäkuuta 2017 15:11
Vastaanottaja: Microsoft/MIMWAL
Kopio: Jokinen, Joonas; Mention
Aihe: Re: [Microsoft/MIMWAL] Iteration support for WAL email activities (#40)


Same place you downloaded last time. In my fork.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Microsoft_MIMWAL_issues_40-23issuecomment-2D316044750&d=DwMCaQ&c=vgc7_vOYmgImobMVdyKsCY1rdGZhhtCa2JetijQZAG0&r=x0nuG-rnw5ZA4o6EKPnLRF5aq7isLObuxXbQfX7jEw8&m=VXfjMoP_kmS1pQitzKYlVc_Te5Gyys_qZL28ga0t0rk&s=IXLXWjDcAkiwupjkRiusS2zfu7FyzDeaQjNT7p1pC64&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AciC417DgAUc-2D1ydgSQeFS9AK9S11c-5FLks5sPKDMgaJpZM4OOLAS&d=DwMCaQ&c=vgc7_vOYmgImobMVdyKsCY1rdGZhhtCa2JetijQZAG0&r=x0nuG-rnw5ZA4o6EKPnLRF5aq7isLObuxXbQfX7jEw8&m=VXfjMoP_kmS1pQitzKYlVc_Te5Gyys_qZL28ga0t0rk&s=NpXZew5yAZ0qBtaCBPRDBX4lJkRnwmYbwyfKAoavWMU&e=>.

**********************************************************************
The information in this e-mail (and any attachments) is intended exclusively for the addressee(s). Any use by a party other than the addressee(s) is prohibited. The information may be confidential in nature and fall under a duty of non-disclosure. If you are not the addressee, please notify the sender and delete this e-mail. KPMG cannot guarantee that e-mail communications are secure or error-free, as information could be intercepted, corrupted, amended, lost, destroyed, arrive late or incomplete, or contain viruses. Any opinions or advice contained in this e-mail are subject to the terms and conditions expressed in the governing KPMG client engagement letter. Please consider the environment before printing this email.

**Comment by NileshGhodekar** [comment]
Thanks for confirmation. I'll promote this for public release over the week-end.

**Comment by NileshGhodekar** [comment]
This is now part of the public release [MIMWAL v2.17.0721.0](https://github.com/Microsoft/MIMWAL/releases/tag/v2.17.0721.0)
