### ISSUE TITLE
Issue on Send Email Notification Activity

### ISSUE THREAD

**Issue by pappa75** [Microsoft/MIMWAL#41]
When using the Send Email Notification Activity in the workflow either with OOB email template or with custom template, the following error is logged in the event viewer and no email is sent by MIM:

WAL (2.17.0414.0): 07/03/2017 13:32:35.5210: The expression '/EmailTemplate[DisplayName = 'Service Account Created']' is invalid.

I have tried the suggested workaround using the ObjectID mentioned at https://social.technet.microsoft.com/Forums/en-US/730297fd-59f5-4676-90d4-3d04ef60cbbe/the-expression-emailtemplatedisplaynamedefault-timed-out-request-email-template-is-invalid?forum=Mimwal but it does not solve the issue and same error appears in event viewer. If using an incorrect display name of the email template, then a different error is logged which is certainly correct as it says that the template cannot be found.

**Comment by NileshGhodekar** [comment]
Can you please paste the complete event log entry? How do you repro this as this error would typically be caught at the design time and not run time.

**Comment by pappa75** [comment]
Here´s more details about the event log entry:
WAL (2.17.0414.0): 07/03/2017 13:32:35.5210: The expression '/EmailTemplate[DisplayName = 'Service Account Created']' is invalid.
Extended Properties:
WorkflowInstanceId: ec44bdd4-30ed-4241-8383-5639a0c7442d
TargetId: 4f8a24b4-37e4-4c9b-a0c4-eba6a741089a
RequestId: 7530de9f-34fe-44ab-9229-de028d494e25
WorkflowDefinitionId: 245e4222-0185-4957-8e00-ebdc597fb644
ActorId: e05d1f1b-3d5e-4014-baa6-94dee7d68c89

There are no errors when the worklow is created or edited in the MIM Portal so the error only appears when the workflow is really run. In this case the issue can be reproduced every time when a new user is created and once it has been synced to Active Directory and MIM sees that the account is now present in AD, it will execute a workflow containing the email notification activity and trying to notify the manager of the user that the account is created etc.

**Comment by NileshGhodekar** [comment]
Interesting. Can you please share the XOML for this workflow from the advanced view to nileshg @ microsoft.com?

**Comment by pappa75** [comment]
Sure I can do that.

**Comment by NileshGhodekar** [comment]
After some investigation, I realised that this is an informational message and not an error. So can you please turn on verbose logging for WAL (change from Warning to Verbose for WAL source name="MicrosoftServices.IdentityManagement.WorkflowActivityLibrary" in the Microsoft.ResourceManagement.Service.exe.config) and it will tell you exactly which email addresses the mail was sent to and the template used.

PS: You'll need to restart the FIM Services after making update to RM.exe.config for it to take effect.

**Comment by NileshGhodekar** [comment]
As investigation offline, this message is informational message only and in no way a real error. The SendEmailNotification activity works as expected.  We'll change the message category from Informational to Verbose. Closing this as a non-issue.
