### ISSUE TITLE
generate a unique value for a set of users

### ISSUE THREAD

**Issue by Eabikhers** [Microsoft/MIMWAL#44]
when running a workflow for a set of users to generate unique account name value , it is getting erros?
so how can i generate account names for a number of users in a set in MIM?

**Comment by NileshGhodekar** [comment]
Closing here. See MIMWAL Forum Thead: https://social.technet.microsoft.com/Forums/en-US/5bf5c26c-aafc-4e1f-92d5-d05c56f22fd0/generate-a-unique-value-for-a-set-of-users?forum=Mimwal
