### ISSUE TITLE
Error Workflow generate unique Value

### ISSUE THREAD

**Issue by timobech** [Microsoft/MIMWAL#45]
Hello,

We are trying to create a get a unique AccountName by following the informations in : 
https://github.com/Microsoft/MIMWAL/wiki/Scenario---Generate-Unique-Account-Name
and we use Values Expression below: 
Left([//Target/LastName],19)+Left([//Target/FirstName],1)
Left([//Target/LastName],18)+Left([//Target/FirstName],1)+[//UniquenessKey]
with different Substr argument (19, 18) we have an generated exception with executed MPR related to our WF:

System.Collections.Generic.KeyNotFoundException: La clé donnée était absente du dictionnaire. à System.ThrowHelper.ThrowKeyNotFoundException() à System.Collections.Generic.Dictionary`2.get_Item(TKey key) à Microsoft.ResourceManagement.Query.QueryParametersGenerator.WriteRequestedAttributes() à Microsoft.ResourceManagement.Query.QueryParametersGenerator.BuildParameterString() à Microsoft.ResourceManagement.Query.QueryProcessor.BuildSqlCommand(Query objectRepresentation, Boolean countResultsOnly) à Microsoft.ResourceManagement.Query.QueryProcessor.ExecuteQuery(Query query, Nullable`1 maximumTime, Boolean& endOfSequence, Boolean countResultsOnly, Int64& resultCount, Int64& executionTime) à Microsoft.ResourceManagement.Query.QueryProcessor.ExecuteQuery(Query query, Boolean& endOfSequence) à Microsoft.ResourceManagement.Data.DataAccess.GetObject(Guid objectId, CultureInfo locale, Guid requestor, String[] attributeNames, Boolean includeInlineRights) à Microsoft.ResourceManagement.Data.DataAccess.GetObject(Guid objectId, String[] attributeNames) à Microsoft.ResourceManagement.ActionProcessor.ActionDispatcher.Read(Guid objectId, CultureInfo locale, Nullable`1 requestor, Nullable`1 resourceTime, String[] requestedAttributes, Boolean includeRights) à Microsoft.ResourceManagement.ActionProcessor.ActionDispatcher.ProcessOutputRequest(RequestType request) à Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteGetAction(RequestType request) à Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteAction(RequestType request) à Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteAction[ResponseBodyType](RequestType request) à Microsoft.ResourceManagement.WebServices.RequestDispatcher.DispatchRequest[ResponseBodyType](RequestType request, Guid requestIdentifier, Object redispatchSingleInstanceKey, Boolean isRedispatch) à Microsoft.ResourceManagement.WebServices.RequestDispatcher.DispatchRequest[ResponseBodyType](RequestType request) à Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.DispatchRequest[TResponseType](RequestType request, Boolean applyAuthorizationPolicy) à Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.ProcessGetWorkItem(ReadRequestWorkItem readWorkItem) à Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.ProcessWorkItem(WorkItem workItem)

The akward thing is that when we use the same argument in the two value expression we donn't have this error, thanks for cheking this.

Regards

**Comment by NileshGhodekar** [comment]
It looks like you made case spelling mistake in the name of an attribute and later corrected it. From the various incidents on this KeyNotFoundException error is to delete and recreate the workflow from scratch and save the new workflow. I suggest you try that.

**Comment by NileshGhodekar** [comment]
I'm closing this issue as this is not related to WAL as per prior investigation on such exception. If the resolution does not work or if there is a simple resolution that recreating from scratch, please do report back.

**Comment by timobech** [comment]
Thank you for your reply, i tried your solution and it worked.
