### ISSUE TITLE
No parallel and a very slow processing of MIMWAL workflows

### ISSUE THREAD

**Issue by henry-1** [Microsoft/MIMWAL#49]
I used FIMWAL2 for years for all workflows and upgraded to MIMWAL 2.17.0927.0
Now I recognised very slow MIM WAL Workflows and no parallel processing
The workflows in essence are using the UpdateResource activity to:
- Lookup DomainConfiguration object to set Domain and DomainConfiguration for users and groups
- Do some regex to get parts of a string attribute to set other string attributes
- Do a BitOr operation on an integer value to set a Boolean attribute in the portal

There are approximately 50.000 objects to to be changed in bulk by two different workflows. 
I tested it on a machine with the following specs:
-  8 cores and  8 GB RAM
- 16 cores and 16 GB RAM
- 64 cores and 64 GB RAM
SQL is installed on a different machine.
It made no difference. The processor load on the MIM server was immediatly up to 100%.

The problem is, that we reach nearly 100% processor usage while just 2-4 workflows run per minute. No significant network or SQL load.
For me it seems like I do something in the workflows that locks SQL or runs through a single thread in the request processor.

The only way I found to reduce the processor load and to get a bit more workflows per minute was to set the max… values in the Microsoft.ResourceManagement.Service.exe.config
<resourceManagementService externalHostName="xxx"
  dataReadTimeoutInSeconds="300" dataWriteTimeoutInSeconds="300"
  maxSimultaneousAuthenticationWorkflows="5"
  maxSimultaneousAuthorizationAndActionWorkflows="5" 
/>

We do not have any Authentication workflows in this scenario. We also do not have any parts of Authorization in the action workflows hit by the problem.

Thanks in advance
Henry

**Comment by NileshGhodekar** [comment]
Probably the processor loads is expected if you have bulk update on 50K object. For you part, just make sure Verbose logging is disabled for MIM WAL **as well as** Microsoft.ResourceManagement.Service ETW as noted in the [Build and Deployment](https://github.com/Microsoft/MIMWAL/wiki/build-and-deployment) Wiki. If that does not help, you can open a support case for MIM and get this investigated.

**Comment by NileshGhodekar** [comment]
@henry-1, I'm closing this thread as there is not much we can do here. As mentioned earlier, if you need further assistance with investigating the perf issue, please open a support case for MIM product.
