### ISSUE TITLE
Delete value expression in Generate unique value deletes the all the following expressions

### ISSUE THREAD

**Issue by UlfLindstrom** [Microsoft/MIMWAL#5]
When deleting a single value expression it seems that that and all the following gets deleted.
In the example 2 and 3 gets deleted if i select to delete 2

1. NormalizeString(Left([//Target/FirstName], 3) + Left([//Target/LastName], 3))
2. NormalizeString(Left([//Target/FirstName], 3) + Left([//Target/LastName], 3))
3. NormalizeString(Left([//Target/FirstName], 3) + Left([//Target/LastName], 2)) + [//UniquenessKey]

**Comment by schmarrap** [comment]
i don't see any difference between 1,2, so sound like normal operation?

**Comment by UlfLindstrom** [comment]
Sorry typo from me, Should be

1.NormalizeString(Left([//Target/FirstName], 2) + Left([//Target/LastName], 2))
2.NormalizeString(Left([//Target/FirstName], 3) + Left([//Target/LastName], 3))
3.NormalizeString(Left([//Target/FirstName], 3) + Left([//Target/LastName], 2)) + [//UniquenessKey]

But the problem is that only line 1 is left when you save you will get an error stating you are missing the UniquessKey witch you will have to manually add again before saving.

**Comment by NileshGhodekar** [comment]
This is a UI bug that affects all activities. If you delete a definition row, it deletes twice as many rows.

**Comment by NileshGhodekar** [comment]
@UlfLindstrom, this is fixed in the v2.16.0130.0. Can you please try?

**Comment by NileshGhodekar** [comment]
Folks, I'm closing this issue as fixed. If you see it still occurring on the latest build, please reopen.
