### ISSUE TITLE
Request Approval

### ISSUE THREAD

**Issue by barnaby81** [Microsoft/MIMWAL#51]
Hello Team,

I have a problem with the Request Approval Activity, when configure this activity and run the my scenario the activity log show errors about the parameters, the some errors are:

- WAL (2.17.0414.0): 12/18/2017 13:20:45.8349: The expression 'xxxxx@xxxxx.com' is invalid. (The  email is correct)

- WAL (2.17.0414.0): 12/18/2017 13:20:45.8974: The expression 'EmailTemplate[DisplayName='Default pending approval email template']' is invalid.

and finally the log shows:

- WorkflowInstance 'c6eab57c-88ac-410d-a945-12708440829a' could not resolve mail message in activity 'authorizationActivity1.CreateApproval.sendApprovalEmail'.  Mail was not sent.

I appreciate your help on this.

Regards

Daniel Mendoza

**Comment by bpalfaro** [comment]
Hey Daniel,

Do you have a forward slash in front of the EmailTemplate keyword?  Ex.  /EmailTemplate[DisplayName='Default pending approval email template']

Thanks,
Bryan

**Comment by barnaby81** [comment]
Hi Bryan,

Yes the expression is by default "/EmailTemplate[DisplayName='Default pending approval email template']".

Regards.

**Comment by NileshGhodekar** [comment]
Both of these are not errors, but verbose messages in the parsing logic. You can ignore.

In the approval activity an email address must resolve to a person (or group) object in the FIMService DB. I think only in the notification activity, it can be any arbitrary  email address.

Sent from my Windows 10 phone

________________________________
