### ISSUE TITLE
Error with Generate unique attributes and  Set initial values for new portal and HR users

### ISSUE THREAD

**Issue by IbrahimOluwadamilare** [Microsoft/MIMWAL#52]
I need help i keep getting the error while the above two work flows are triggered.

Microsoft.ResourceManagement.WorkflowDataExchangeException:  System.Collections.Generic.KeyNotFoundException: The given key was not present  in the dictionary. at System.ThrowHelper.ThrowKeyNotFoundException() at  System.Collections.Generic.Dictionary`2.get_Item(TKey key) at  Microsoft.ResourceManagement.Query.QueryParametersGenerator.WriteRequestedAttributes()  at  Microsoft.ResourceManagement.Query.QueryParametersGenerator.BuildParameterString()  at Microsoft.ResourceManagement.Query.QueryProcessor.BuildSqlCommand(Query  objectRepresentation, Boolean countResultsOnly) at  Microsoft.ResourceManagement.Query.QueryProcessor.ExecuteQuery(Query query,  Nullable`1 maximumTime, Boolean& endOfSequence, Boolean countResultsOnly,  Int64& resultCount, Int64& executionTime) at  Microsoft.ResourceManagement.Data.DataAccess.GetObject(Guid objectId,  CultureInfo locale, Guid requestor, String[] attributeNames, Boolean  includeInlineRights) at  Microsoft.ResourceManagement.Data.DataAccess.GetObject(Guid objectId, String[]  attributeNames) at  Microsoft.ResourceManagement.ActionProcessor.ActionDispatcher.Read(Guid  objectId, CultureInfo locale, Nullable`1 requestor, Nullable`1 resourceTime,  String[] requestedAttributes, Boolean includeRights) at  Microsoft.ResourceManagement.ActionProcessor.ActionDispatcher.ProcessOutputRequest(RequestType  request) at  Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteGetAction(RequestType  request) at  Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteAction(RequestType  request) at  Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteAction[ResponseBodyType](RequestType  request) at  Microsoft.ResourceManagement.WebServices.RequestDispatcher.DispatchRequest[ResponseBodyType](RequestType  request, Guid requestIdentifier, Object redispatchSingleInstanceKey, Boolean  isRedispatch) at  Microsoft.ResourceManagement.WebServices.RequestDispatcher.DispatchRequest[ResponseBodyType](RequestType  request) at  Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.DispatchRequest[TResponseType](RequestType  request, Boolean applyAuthorizationPolicy) at  Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.ProcessGetWorkItem(ReadRequestWorkItem  readWorkItem) at  Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.ProcessWorkItem(WorkItem  workItem) at  Microsoft.ResourceManagement.Workflow.Activities.ReadResourceActivity.ProcessRequestResponse(Object  sender, QueueEventArgs e) at  System.Workflow.ComponentModel.ActivityExecutorDelegateInfo`1.ActivityExecutorDelegateOperation.Run(IWorkflowCoreRuntime  workflowCoreRuntime) at System.Workflow.Runtime.Scheduler.Run()
--

**Comment by NileshGhodekar** [comment]
Have you searched the TechNet forums / Web for this error? This is not a MIMWAL issue, but a MIM issue and you get this error when there is a typo in the attribute names (all names are case sensitive). I'm closing this issue now.
