### ISSUE TITLE
Return and use multivalue attribute from powershell activity

### ISSUE THREAD

**Issue by UlfLindstromLumagate** [Microsoft/MIMWAL#53]
I want to build a hash table with multiple values both single value and multi-value but when i add the multi-value in the hash it's failing when i want to do. Also tried to iterate the return value wit same result.

:Second activity
InsertValues([//WorkflowData/AddEntitlements]) -> [//Target/ActiveEntitlements]

======== Works ============
PARAM(
    $AssignedEntitlements = @("+test","-av","+mv")
)

$Result = @{}
$AddEntitlements = @()
Foreach($item in $AssignedEntitlements) {
    If($item.StartsWith('+')) { $AddEntitlements += $item }
}
Return $AddEntitlements
=========================

======== Failes =============
$Result = @{}
$AddEntitlements = @()
$RemoveEntitlements = @()

....Populating arrays.....

$Result.Add('AddEntitlements',$AddEntitlements)
$Result.Add('RemoveEntitlements',$RemoveEntitlements)

Return $Result
==============
System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: The type System.Object[] may not be used in this context. at System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(String name, String ns, Object o, Boolean xsiType) at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterRequestParameter.Write1_Object(String n, String ns, Object o, Boolean isNullable, Boolean needType) at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterRequestParameter.Write8_UpdateRequestParameter(String n, String ns, UpdateRequestParameter o, Boolean isNullable, Boolean needType) at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterRequestParameter.Write11_RequestParameter(Object o) --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id) at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o) at Microsoft.ResourceManagement.WebServices.WSResourceManagement.RequestType.AddParameter(RequestParameter parameter) at Microsoft.ResourceManagement.WebServices.WSResourceManagement.RequestType.SetRequestParameters(OperationType operation, UniqueIdentifier targetObject, List`1 requestParameters) at Microsoft.ResourceManagement.WebServices.WSResourceManagement.RequestType..ctor(UniqueIdentifier creator, UniqueIdentifier targetIdentifier, OperationType operation, List`1 requestParameters, CultureInfo locale, Boolean isChildRequest, Guid cause, Boolean maintenanceMode, UniqueId messageIdentifier, UniqueIdentifier requestContextIdentifier) at Microsoft.ResourceManagement.WebServices.RequestDispatcher.CreateRequest(UniqueIdentifier requestor, UniqueIdentifier targetIdentifier, OperationType operation, String businessJustification, List`1 requestParameters, CultureInfo locale, Boolean isChildRequest, Guid cause, Boolean doEvaluation, Nullable`1 serviceId, Nullable`1 servicePartitionId, UniqueId messageIdentifier, UniqueIdentifier requestContextIdentifier, Boolean maintenanceMode) at Microsoft.ResourceManagement.WebServices.RequestDispatcher.CreateRequest(UniqueIdentifier requestor, UniqueIdentifier targetIdentifier, OperationType operation, String businessJustification, List`1 requestParameters, CultureInfo locale, Boolean isChildRequest, Guid cause) at Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.CreateRequest(UniqueIdentifier requestor, UniqueIdentifier objectId, OperationType operation, List`1 requestParameters, Guid parentRequest) at Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.ProcessPutWorkItem(UpdateRequestWorkItem updateWorkItem) at Microsoft.ResourceManagement.Workflow.Hosting.RequestWorkItemProcessor.ProcessWorkItem(WorkItem workItem)

**Comment by NileshGhodekar** [comment]
[InsertValues](https://github.com/Microsoft/MIMWAL/wiki/InsertValues-Function) function takes a List<> object type (and not array) and anything else is treated as a single object. The first script is working because the array is getting unwind on the returned pipeline and then the activity is packaging it back as a List<> (List< string > in this case). Try with List< string >.
