### ISSUE TITLE
Wiki Example incorrect https://github.com/Microsoft/MIMWAL/wiki/DateTimeFormat-Function

### ISSUE THREAD

**Issue by weyto** [Microsoft/MIMWAL#57]
Hi,
the example on the wiki page https://github.com/Microsoft/MIMWAL/wiki/DateTimeFormat-Function

should be
DateTimeFormat(DateTimeNow(),"dd/MM/yyyy HH:mm:ss.ffff")

instead of
DateTimeFormat(DateTimeNow(),"dd/MM/YYYY HH:mm:ss.ffff")

**Comment by NileshGhodekar** [comment]
Thanks! Made the edit.
