### ISSUE TITLE
DateTimeToFileTimeUTC year loss

### ISSUE THREAD

**Issue by Amethi** [Microsoft/MIMWAL#59]
With an `EmployeeEndDate` of `05/10/2018 01:00:00` 

Using this expression:
```IIF(IsPresent([//Target/EmployeeEndDate]), DateTimeToFileTimeUTC([//Target/EmployeeEndDate]),  9223372036854775807)```

I get `131831712000000000` back, which using http://www.datetimetoticks-converter.com or http://tickstodatetime.com shows that converts back as `05/10/0418 00:00:00`, so we're losing 1600 years.

Am I misunderstanding what's expected here, or could there be a bug? I thought you could convert both ways. I'm just trying to validate what will be set in AD (I can't run an export on this system ATM to confirm)

**Comment by NileshGhodekar** [comment]
Windows file time starts at 1601 AD, not 01 AD. So try converting back in PowerShell for example on a Windows machine.
