### ISSUE TITLE
XPath expression in Conflict Filter (Generate Unique Value)

### ISSUE THREAD

**Issue by FredrikMelby** [Microsoft/MIMWAL#61]
Hi, i have a problem with the "Conflict Filter" expression when developing a workflow to generate unique email aliases. Im trying to get MIMWAL to validate the output value against existing users proxy addresses to ensure it's a unique value (ProxyAddressCollection attribute in MIM).

The server is running MIMWAL version 2.18.0318 and MIM build 4.4.1749.

The workflow is configured as this:

Value Expression 1:
`RegexReplace(RegexReplace(TitleCase(NormalizeString(LowerCase(Trim([//Target/FirstName]) + " " + Trim([//Target/LastName])),"æ:a|ø:o|å:a")),"[.]\s|\s+","."),"[^a-zA-Z0-9-.]","")`

Value Expression 2:
`RegexReplace(RegexReplace(TitleCase(NormalizeString(LowerCase(Trim([//Target/FirstName]) + " " + Trim([//Target/LastName])),"æ:a|ø:o|å:a")),"[.]\s|\s+","."),"[^a-zA-Z0-9-.]","")+[//UniquenessKey]`

Target Attribute:
`[//Target/MailNickname]`

I have tried different formats when configuring the Conflict Filter - but get the same error every time I trigger the workflow agains a user:
![image](https://user-images.githubusercontent.com/29274188/47648271-d2dc9f80-db79-11e8-8014-4a86f9f8a2a3.png)

Event Log:
![image](https://user-images.githubusercontent.com/29274188/47648336-07e8f200-db7a-11e8-8cf7-9b4f98136c3f.png)

Conflict Filters I have tried so far:

```
/Person[starts-with(ProxyAddressCollection,"smtp:[//Value]@")]
/Person[starts-with(ProxyAddressCollection,"smtp:[//Value]")]
/Person[starts-with(ProxyAddressCollection,'smtp:[//Value]@')]
/Person[starts-with(ProxyAddressCollection,'smtp:[//Value]')]
```

The only expression that I have managed to run successfully is this where i don't start the "starts-with" operator with the "smtp:" string:
`/Person[starts-with(ProxyAddressCollection,'[//Value]')]`

Complete XOML of current workflow:
```
<ns0:SequentialWorkflow ActorId="00000000-0000-0000-0000-000000000000" RequestId="00000000-0000-0000-0000-000000000000" x:Name="SequentialWorkflow" TargetId="00000000-0000-0000-0000-000000000000" WorkflowDefinitionId="00000000-0000-0000-0000-000000000000" xmlns:ns1="clr-namespace:MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Activities;Assembly=MicrosoftServices.IdentityManagement.WorkflowActivityLibrary, Version=2.18.318.0, Culture=neutral, PublicKeyToken=d4c6b0a02014cd86" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/workflow" xmlns:ns2="clr-namespace:MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.ComponentActivities;Assembly=MicrosoftServices.IdentityManagement.WorkflowActivityLibrary, Version=2.18.318.0, Culture=neutral, PublicKeyToken=d4c6b0a02014cd86" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:ns0="clr-namespace:Microsoft.ResourceManagement.Workflow.Activities;Assembly=Microsoft.ResourceManagement, Version=4.4.1749.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
	<ns1:GenerateUniqueValue ActivityExecutionCondition="" ActivityDisplayName="Generate unique alias" PublicationTarget="[//Target/MailNickname]" ConflictFilter="/Person[starts-with(ProxyAddressCollection,'[//Value]')]" UniquenessSeed="2" QueryLdap="False" x:Name="actionActivity1">
		<ns1:GenerateUniqueValue.ValueExpressions>
			<ns3:ArrayList xmlns:ns3="clr-namespace:System.Collections;Assembly=mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
				<ns4:String xmlns:ns4="clr-namespace:System;Assembly=mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">RegexReplace(RegexReplace(TitleCase(NormalizeString(LowerCase(Trim([//Target/FirstName]) + " " + Trim([//Target/LastName])),"æ:a|ø:o|å:a")),"[.]\s|\s+","."),"[^a-zA-Z0-9-.]","")</ns4:String>
				<ns4:String xmlns:ns4="clr-namespace:System;Assembly=mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">RegexReplace(RegexReplace(TitleCase(NormalizeString(LowerCase(Trim([//Target/FirstName]) + " " + Trim([//Target/LastName])),"æ:a|ø:o|å:a")),"[.]\s|\s+","."),"[^a-zA-Z0-9-.]","")+[//UniquenessKey]</ns4:String>
			</ns3:ArrayList>
		</ns1:GenerateUniqueValue.ValueExpressions>
		<ns1:GenerateUniqueValue.LdapQueriesTable>
			<ns3:Hashtable xmlns:ns3="clr-namespace:System.Collections;Assembly=mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
				<ns4:Int32 xmlns:ns4="clr-namespace:System;Assembly=mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">0<x:Key><ns4:String>Count</ns4:String></x:Key></ns4:Int32>
			</ns3:Hashtable>
		</ns1:GenerateUniqueValue.LdapQueriesTable>
	</ns1:GenerateUniqueValue>
</ns0:SequentialWorkflow>
```

**Comment by FredrikMelby** [comment]
Done som more testing today and I see some strange behaviour. Take these screen shots from the Event Log after running the workflow against a user:
![image](https://user-images.githubusercontent.com/29274188/47720876-31278200-dc4f-11e8-850a-a544d735972d.png)


![image](https://user-images.githubusercontent.com/29274188/47720860-2836b080-dc4f-11e8-9439-12260ed2bf5f.png)

First it says that it found a user matching my conflict filter (not the target user) and in the second event log it says "No Conflict Found". When I search up the ObjectID returned in the first event entry, I find my test user containing the entries that should be a conflict:
![image](https://user-images.githubusercontent.com/29274188/47721434-62ed1880-dc50-11e8-9380-a7e80770234f.png)

Conflict filter:
`/Person[starts-with(ProxyAddressCollection,'[//Value]')]`

Expression:
`"smtp:"+RegexReplace(RegexReplace(TitleCase(NormalizeString(LowerCase(Trim([//Target/FirstName]) + " " + Trim([//Target/LastName])),"æ:a|ø:o|å:a")),"[.]\s|\s+","."),"[^a-zA-Z0-9-.]","")+"@"`

**Comment by NileshGhodekar** [comment]
Hi @FredrikMelby, this is an unintended use of starts-with function in the conflict filter. See the documented usage at https://github.com/Microsoft/MIMWAL/wiki/Generate-Unique-Value-Activity#conflict-filter.
 For your usecase, the only thing that will be suppored with be the equality operator as in:
/Person[ProxyAddressCollection='smtp:[//Value]'].

Also take a look at https://social.technet.microsoft.com/wiki/contents/articles/37997.mim2016-mimwal-create-workflow-for-changing-e-mail-address.aspx  if that is what you need to achieve.

**Comment by FredrikMelby** [comment]
ok, I did an rewrite of the conflict filter so it looks like this now:
`/Person[((ProxyAddressCollection = 'smtp:[//Value]@test.com') or (ProxyAddressCollection = 'smtp:[//Value]@test2.com') or (ProxyAddressCollection = 'smtp:[//Value]@test3.com')) and not(ObjectID = '[//Target/ObjectID]')]`. 

This works as intended and I can now check that the aliases generated is unique across all my SMTP domains. My hope was that I didn't have to specify all my domains in the workflow conflict filter, by using the "starts-with" operator. But this gives me the same result, with a little more configuration.

**Comment by NileshGhodekar** [comment]
Hi @FredrikMelby,

The starts-with() optimisation is now not turned on by default. So the latest build should give you the expected results. So now you should not need to define specify all my domains in the workflow conflict filter and your original XPath should work without crashing. Please try it out and see how it goes.
