### ISSUE TITLE
SqlParameter is not marked as serializable

### ISSUE THREAD

**Issue by mrmueller** [Microsoft/MIMWAL#62]
We are using ExecuteSqlNonQuery to write workflow results to SQL. Additionally, when errors occur, we send emails (send email activity)

As far as i can tell, when the send email activity is called, the workflow seems to get serialized. Serialization fails if there are SqlParameters present in the workflow.

The following error is logged in the request and in eventlog:
`Type 'System.Data.SqlClient.SqlParameter' in Assembly 'System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable
`
We can work around the issue by setting all the parameters to Null():
![mimwal_sqlparameter](https://user-images.githubusercontent.com/9515311/48213309-cc220980-e37d-11e8-9e0b-659f1dabf097.PNG)

Can we add this to the documentation or fix it? Did cost us some time in debugging...

**Comment by NileshGhodekar** [comment]
Hi @mrmueller, thanks for reporting this issue. Can you quickly check if you see the same behaviour if the workflow gets dehydrated when Add Delay activity is used? So a simple workflow with this activity followed by Add Delay of a couple of minutes and see if it raised the same error too.

**Comment by mrmueller** [comment]
Hi @NileshGhodekar 

I can confirm that using the Add Delay activity produced the same result.

`Request Identifier: c6199f20-e340-448b-bcd0-cd90e21cb036 Workflow Instance  Identifier: e063bc9f-b2c5-4046-98fa-ac1ff60c173a Workflow Definition Identifier:  3dd7e379-726d-487a-9f99-6b9d9c0dbdae Workflow Exception:  System.Runtime.Serialization.SerializationException: Type  'System.Data.SqlClient.SqlParameter' in Assembly 'System.Data, Version=2.0.0.0,  Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.  at  System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType  type) at  System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type,  StreamingContext context) at  System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()  at  System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object  obj, ISurrogateSelector surrogateSelector, StreamingContext context,  SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter  objectWriter) at  System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo  objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo) at  System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(WriteObjectInfo  objectInfo, NameInfo arrayElemTypeNameInfo, Object data) at  System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo  objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo) at  System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo  objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo) at  System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object  graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck) at  System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream  serializationStream, Object graph, Header[] headers, Boolean fCheck) at  System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream  serializationStream, Object graph) at  System.Workflow.ComponentModel.Activity.Save(Stream stream, IFormatter  formatter) at  System.Workflow.Runtime.Hosting.WorkflowPersistenceService.GetDefaultSerializedForm(Activity  activity) at  System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService.SaveWorkflowInstanceState(Activity  rootActivity, Boolean unlock) at  Microsoft.ResourceManagement.Workflow.Hosting.ResourceManagementSqlWorkflowPersistenceService.SaveWorkflowInstanceState(Activity  rootActivity, Boolean unlock)
`

![mimwal_sqlparameter_delay](https://user-images.githubusercontent.com/9515311/48271555-de16b180-e43c-11e8-8b84-dfd25f0ed80b.PNG)

**Comment by NileshGhodekar** [comment]
Thanks! If Nullifying the variables is the solution then code can be added to clear them out once the activity execution completes. Let me check.

**Comment by NileshGhodekar** [comment]
Hi @mrmueller, I tried this, but I'm not able to get the repro :( 

Here is my SQL activity:
CreateSqlParameter("AuxDB","@FirstName", [//Target/FirstName]) => $FirstName
CreateSqlParameter("AuxDB","@LastName", [//Target/LastName]) => $LastName
ExecuteSqlScalar("AuxDB", "Select @FirstName+@LastName", $FirstName, $LastName) => $AccountName

Can you provide a simple repro? Probably some datatype is causing this issue?

**Comment by NileshGhodekar** [comment]
Sorry, yes, I've a repro now.

**Comment by NileshGhodekar** [comment]
I'm closing this issue as fixed in the latest release.

**Comment by mrmueller** [comment]
Sorry for the delay, I was out of the office. The issue does not occur with MIMWAL v2.18.1110.0. 
Thanks @NileshGhodekar . Great speed. 👍
