### ISSUE TITLE
Build 4.13496 has ben removed

### ISSUE THREAD

**Issue by SylleRylle** [Microsoft/MIMWAL#65]
The FIM R2 build 4.1.3496 (KB2906832) which you recommend for the MIMWAL compile has been been removed from Microsoft.
Is the next build as good, or can you provide a download link?

**Comment by NileshGhodekar** [comment]
Hi @SylleRylle, you can get the files from the hotlinks provided on the individual files on the build and deploy wiki or you can get it from any higher build available to you. If you do get them from a higher version build available to you, you need to make sure that the servers you'd be deploying MIMWAL on are at the same or a higher build than what you referenced for compiling the code.
