### ISSUE TITLE
Conflict Filter /Person[AccountName = '[//Value]'] is wrong. Look inside for the correct expression.

### ISSUE THREAD

**Issue by guyhorn1964** [Microsoft/MIMWAL#66]
It should be Conflict Filter /Person[AccountName]  = '[//Value]']

**Comment by NileshGhodekar** [comment]
Hi @guyhorn1964 , what you have provided is an absolutely wrong XPath syntax. Does not even have a matching number of opening and closing square brackets let alone the valid XPath syntax. I'm closing this issue.
