### ISSUE TITLE
Problem with Conflict filter using starts-with XPath function (Generate Unique Value)

### ISSUE THREAD

**Issue by Identitry** [Microsoft/MIMWAL#67]
Hi!
I've got a Generate Unique Activity to generate a unique Domino CN. I've already read the closed issue #61 posted by Fredrik Melby but I think my case is similar but I don't add extra characters next to the [//Value] in the filter and I need to understand why my implementation doesn't work.

**Conflict filter:** /Person[(starts-with(FullNames, '[//Value]')) and (not(ObjectID = '[//Target/ObjectID]'))]
FullNames attribute is multi valued and contains all current Domino FullName values for users to check against.

**Value Expressions:**
1. EscapeDNComponent(Concatenate("CN=",[//Target/FirstName]," ",[//Target/LastName]))+","
2. EscapeDNComponent(Concatenate("CN=",[//Target/FirstName]," X ",[//Target/LastName]))+","
3. EscapeDNComponent(Concatenate("CN=",[//Target/FirstName]," Y ",[//Target/LastName]))+","
4. EscapeDNComponent(Concatenate("CN=",[//Target/FirstName]," ",[//Target/LastName],[//UniquenessKey]))+","

The expressions all ends with a comma (not within the EscapeDNComponent function) in order to ensure the filter doesn't catch persons with just a similar value for FullName. The filter works great using for example a temporary Search Scope however in the activity a duplicate is not found even though it exist.
Checking against the full FullName values would be to hard to handle.

//Henrik Nilsson

**Comment by NileshGhodekar** [comment]
Hi @Identitry, the starts-with() optimisation is now not turned on by default. So the latest build should give you the expected results. Please try it out and see how it goes.

**Comment by NileshGhodekar** [comment]
Closing this issue as a DCR was implemented for this and release as [v2.19.0112.0](https://github.com/Microsoft/MIMWAL/releases/tag/v2.19.0112.0).
