### ISSUE TITLE
Question: Creating Account Names for Security Groups via WAL

### ISSUE THREAD

**Issue by IrwinSmith** [Microsoft/MIMWAL#7]
Is it possible to create unique Account Names for Security Groups via the WAL?  I do not want my users entering the Account Name for Security Groups and would rather have the Account name generated by either a unique 20 character string or the group name provided (all spaces and special characters would be replaced with an underscore).

**Comment by Amethi** [comment]
Active Directory will create a sAMAccountName if you don't specify one. Same goes for users, so you wouldn't need MIM to do this for you.

**Comment by IrwinSmith** [comment]
I’m using the MIM portal to create Security Groups and the AccountName is a required field.  If I change the form so that the AccountName is not required the Group Validation workflow reports a value is required (Group validation failed: A values is required for the account name attribute).

**Comment by Amethi** [comment]
Ah I see, well the way I have done this in the past is to use a **Generate Unique Value Activity** to generate the sAMAccountName for me. So you still need to modify the RCDC to remove the attribute from the UI and then use Generate Unique Value Activity to build a sAMAccountName value that looks like this format : `MIMGroups-{iterator}`.

The activity will then try and create values such as **MIMGroups-1**, and then **MIMGroups-2**, etc. You can increase the robustness of this by having the activity check not only the MIM database to make sure the value is unique, but also Active Directory via the LDAP query option.

More info:
https://github.com/Microsoft/MIMWAL/wiki/Generate-Unique-Value-Activity

**Comment by IrwinSmith** [comment]
Thanks.  I’ve being trying this option without any luck.  I’ll continue working on it.

**Comment by NileshGhodekar** [comment]
Yes, you can check the Wiki for Generate Unique Value activity. I'm closing this issue. For general questions and discussion, please use the MIMWAL TechNet forum. If you have a bug to report or a feature to suggest, feel free to raise the issue. Thanks!
