### ISSUE TITLE
Powershell 2.0 deprecated

### ISSUE THREAD

**Issue by gibazza** [Microsoft/MIMWAL#70]
Hi, As PowerShell version 2 is now deprecated is MIM and MIMWAL going to be updated so that can utilise a later version of the .NET framework so that it can support powershell v3.0 and later?

https://blogs.msdn.microsoft.com/powershell/2017/08/24/windows-powershell-2-0-deprecation/

**Comment by NileshGhodekar** [comment]
I cannot comment on the plans for the support of a later version of .NET Framework in MIM, but given the mainstream and extended support timelines for .NET 3.5 SP1, I expect PowerShell 2.0 to be continues to be supported as well for next 10 years, well beyond the support timeline for MIM.  As for MIMWAL, the wiki already documents how to run PowerShell 3.0+ scripts/ cmdlets, so I'll close this issue for now and wait until MIM to start supporting higher version of .NET Framework.
