### ISSUE TITLE
build-and-deployment says you can't use VS 2017 but I seem to be able to use VS 2018

### ISSUE THREAD

**Issue by kendall18** [Microsoft/MIMWAL#71]
The https://github.com/Microsoft/MIMWAL/wiki/build-and-deployment page states that Visual Studio 2017 cannot be used to build the project. However I seem to been able to use the project fine with VS 2017 after installing .net 3.5 on the computer and following the instructions at: https://code-coverage.net/windows-workflow-foundation-build-errors-in-visual-studio-2017/.

**Comment by NileshGhodekar** [comment]
Hi @kendall18, thanks! The fully qualified answer is at: https://developercommunity.visualstudio.com/content/problem/26418/legacy-workflow-foundation-project-wont-load.html. Hence, right now no plan to update the wiki statement as VS 2015 is still widely available, so I'll close this issue.
