### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by guyhorn1964** [Microsoft/MIMWAL#72]
MIMWAL is a great piece of software. While installing it I encountered some imperfections. So let’s make things better.

First of all the installation script ‘register.ps1’ is only suitable if your server has two roles installed: Portal and FIMService. As Microsoft itself advises not to do that in s large environment that’s obviously not the way to go. If you try you will get in both servers annoying errors that can be ignored. But I don’t like my scream bleeding red. So I adjusted the installation script. Actually I created two scripts that can be run separately
error-free. You can find the modified scripts here.

 Then I also had some problems with the
dll’s. Now that’s the first time I have problems with that but the solution is
worth documenting it.            

The error:

PS
C:\SolutionOutput> .\Register.ps1 -PortalSiteName “MIM Portal”

DEBUG:
Registering assembly in GAC:
‘C:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll’

DEBUG:
Microsoft (R) .NET Global Assembly Cache Utility.  Version 3.5.21022.8

Copyright
(c) Microsoft Corporation.  All rights reserved.

 

Failure
adding assembly to the cache: Strong name signature could not be verified.  Was
the assembly built delay-signed?

 

Error
Registering assembly in GAC:
‘C:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll’

At
C:\SolutionOutput\Register.ps1:76 char:13

+
throw (“Error Registering assembly in GAC: ‘$assemblyName …

+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    +
CategoryInfo          : OperationStopped: (Error Registeri…tyLibrary.dll’
:String) [], RuntimeException

    +
FullyQualifiedErrorId : Error Registering assembly in GAC:
‘C:\SolutionOutput\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll’

 The solution:

Place the files somewhere. E.G. in C:\SolutionOutput.

 Set-Location C:\SolutionOutput

$dlls = Get-ChildItem -Filter ‘*dll’

$dlls.name

foreach ($item in $dlls)

{

    .\SN -Vr $item.name

}

Set-Location .\dlls

$dlls = Get-ChildItem -Filter ‘*dll’

$dlls.name

foreach ($item in $dlls)

{

    .\SN -Vr $item.name

}
[Register-MIMWALIntoFIMSservice.txt](https://github.com/Microsoft/MIMWAL/files/3002497/Register-MIMWALIntoFIMSservice.txt)
[Register-MIMWALIntoPortal.txt](https://github.com/Microsoft/MIMWAL/files/3002498/Register-MIMWALIntoPortal.txt)

**Comment by NileshGhodekar** [comment]
Hi @guyhorn1964, you registering the dlls with -Vr switch to skip the strong name validation. Not recommended for a production deployment. You should follow the build wiki and replace the .snk in the MIMWAL sourcecode with your own. Also having two separate scripts for installation is one too many. If you add the logic for detecting which components are installed on the given server in the existing script and send a pull request, then that will be the way to go forward. Closing this issue now.
