### ISSUE TITLE
Send Email Notification Activety String containing GUID

### ISSUE THREAD

**Issue by makauf** [microsoft/MIMWAL#74]
Hi Nilesh,

I just stumbled upon an issue i had to workaround today.
my use case is as follows:
I have to send an email notification with an activation link (Redeem-URL) from another system to the end user.
The URL looks someting like this:
https://domain.com/redeem/?tenant=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&user=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

The Value is saved on in an attribute on the [//Target].

After the activiety gets executed i receive the following Error:

> The Workflow Instance '5e2922a9-0164-4d26-b004-ed2e4dc2f1a8' encountered an internal error during processing. Contact your system administrator for more information.

In the Eventlog:

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.ResourceManagement.WFActivities.Resolver.GetDisplayStringFromGuid(Guid id, String[] expansionAttributes)
>    at Microsoft.ResourceManagement.WFActivities.Resolver.ReplaceGuidWithTemplatedString(Match m)
>    at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
>    at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
>    at Microsoft.ResourceManagement.WFActivities.Resolver.GetStringAttributeValue(Object attribute)
>    at Microsoft.ResourceManagement.WFActivities.Resolver.ResolveEvaluatorWithoutAntiXSS(String match, ResolverOptions resolveOptions)
>    at Microsoft.ResourceManagement.WFActivities.Resolver.ResolveEvaluatorForWithAntiXSS(String match, ResolverOptions resolveOptions)
>    at Microsoft.ResourceManagement.WFActivities.Resolver.ReplaceMatches(String input, Boolean useAntiXssEncoding, ResolverOptions resolveOptions)
>    at Microsoft.ResourceManagement.Workflow.Hosting.EmailNotificationServiceImpl.ResolveMailMessage(Guid requestId, Guid targetId, Guid actorId, Dictionary`2 workflowDictionary, String toLine, String ccLine, String bccLine, Guid emailTemplateIdentifier, EmailResolutionOptions options, String& failedToResolvePrincipals)
>    at Microsoft.ResourceManagement.Workflow.Activities.EmailNotificationActivity.ResolveMail(Object sender, EventArgs e)
>    at System.Workflow.ComponentModel.Activity.RaiseEvent(DependencyProperty dependencyEvent, Object sender, EventArgs e)
>    at System.Workflow.Activities.CodeActivity.Execute(ActivityExecutionContext executionContext)
>    at System.Workflow.ComponentModel.ActivityExecutor`1.Execute(T activity, ActivityExecutionContext executionContext)
>    at System.Workflow.ComponentModel.ActivityExecutor`1.Execute(Activity activity, ActivityExecutionContext executionContext)
>    at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
>    at System.Workflow.Runtime.Scheduler.Run()

After a bit of troubleshooting, i found a workaround:
In the Workflow lookup Variables i just do a `ReplaceString([//Target/RedeemURL],"-","%2D")` into WorkflowData.

I think the send mail notification should not try to resolve GUID's in this way - or at least if it can't find a matching object for the guid (because these guids aren't stored anywhere in the service) it fall should fallback and send the guids as string.

Kind Regards

**Comment by NileshGhodekar** [comment]
Hi @makauf,

Unfortunately, there is not much we can do in MIMWAL apart from the workaround you already implemented as if you look at the stack trace carefully, you'd notice that the error is originating in the MIM source code. So you'll need to raise this as a MIM Product issue to get a proper fix.

Personally, I'm aware that MIM resolver logic will try to resolve all GUIDs and log a warning in the event log , but I've not seen it crash out before. @EugeneSergeev , new bug?

I'll close this issue here as it's not a MIMWAL issue.

**Comment by makauf** [comment]
Thanks Nilesh for the quick response and sorting it out.
i've spoken to a colleague of mine and he told me this behaviour already exists since years.
