### ISSUE TITLE
How to approve for modification of person on HRMS

### ISSUE THREAD

**Issue by diepkv** [microsoft/MIMWAL#79]
Hello
Our system typical have 4 role below:

1. HRMS: Human Resources Management System
2. MIM
3. AD
4. ADFS
 Synchronization flow HRMS => MIM => AD with 3 MA (HRMS, MIM, AD), 3 MPR (HR, MIM outbound, AD inbound).

For adding new person on HRMS I using this MIMWAL to approve / reject before creating as guide it's work very nice

I'm newbie, please tell me how to config for approving in case of modification person on HRMS (fullname, Job title , disable user..) with this solution 

Thank you for any suggestion!

**Comment by diepkv** [comment]
@NileshGhodekar please help me
Thank you so much!

**Comment by NileshGhodekar** [comment]
Hi @diepkv, this is a strange use case. HR is supposed to be authoritative for the attributes they are updating in HR system, so surprising that you need approval for this. If you need approval for any attribute updates, you need to come via "front" door i.e. either via MIM portal or via MIM Service. Anything that comes via sync engine "back door" is already committed in the system so approval does not make sense (are you then going to rollback changes made in HR?). If you insist on coming via "back door" then nless you create additional set of shadow attribute that you push these changes to first before copying on to the real / permanent attributes, you cannot implement approval. I'll close this thread hear as this is more of a solution / design issue than a MIMWAL bug/issue. These issue are best posted on the TechNet forum.
