### ISSUE TITLE
Localization of DateTimeFormat

### ISSUE THREAD

**Issue by SteinIP** [microsoft/MIMWAL#80]
Was asked to provide datestamps in emails, in a hard-to-mistake format: 6.November 2019.

Unfortunatly attempts to use DateTimeFormat results in months using english, which is not sufficient for this customer. So I resorted to Powershell to format my date - (get-date).ToString("dd.MMMM yyyy", [System.Globalization.CutlureInfo]::CreateSpecificCulture("no-NB")). 

Could this be integrated into DateTimeFormat as an optional parameter? Something like DateTimeFormat(DateTimeNow(),"dd.MMMM yyyy", "no-NB"). As it is clearly present in the underlying .net framework, I belive it would require only a very minor effort to implement..

**Comment by NileshGhodekar** [comment]
Thanks @SteinIP  for the suggestion. Yes this is something that is fairly quick to implement. Any takers from the community? :) I'll keep this open until this change is implemented.

**Comment by NileshGhodekar** [comment]
Implemented in the build 2.20.0523.0.
