### ISSUE TITLE
MIMWAL logging and SP2

### ISSUE THREAD

**Issue by wiemerr** [microsoft/MIMWAL#82]
I have applied MIM SP2 to a DEV instance where MIMWAL 2.19 is running.  After SP2 the normal Information log data is missing.  the MIMWAL workflows run fine.

If I change to Verbose I see warnings and errors but still no Information level data.

Any suggestions for how to restore Information level log events?

**Comment by NileshGhodekar** [comment]
Hi @wiemerr, it may be worth checking that you are not mistakenly updating the switchValues in the config sections that are commented out.

**Comment by wiemerr** [comment]
Thanks for responding.  MIMWAL is great!

I have reproduced the pattern in a second DEV lab with SP2.  I am certain I am not changing anything but the Warning to Verbose in the config file.

When I set the config to Verbose logging the only thing I get in the event log are the following at a rate a little slower that what I would expect to see for Information events.

Request Identifier: bb9f8815-cb82-4890-9966-99a7ce1778a5
Workflow Instance Identifier: 8a91c4ee-c9ed-4cfa-a7da-be85bfe79ac9
Workflow Definition Identifier: 0fa89024-b8c3-4fdc-993f-755a61f688d8
Workflow Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Workflow.ComponentModel.Serialization.ActivitySurrogate.ActivitySerializedRef.System.Runtime.Serialization.IDeserializationCallback.OnDeserialization(Object sender)
   at System.Runtime.Serialization.DeserializationEventHandler.Invoke(Object sender)
   at System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at System.Workflow.ComponentModel.Activity.Load(Stream stream, Activity outerActivity, IFormatter formatter)
   at System.Workflow.Runtime.Hosting.WorkflowPersistenceService.RestoreFromDefaultSerializedForm(Byte[] activityBytes, Activity outerActivity)
   at System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService.LoadWorkflowInstanceState(Guid id)
   at Microsoft.ResourceManagement.Workflow.Hosting.ResourceManagementSqlWorkflowPersistenceService.LoadWorkflowInstanceState(Guid Id)

**Comment by wiemerr** [comment]
And looking deeper the event I just posted is coming from a previously persisted workflow.  I am not seeing any events from the currently running workflows.  When I find the WF GUID from the event above I see this:

Jan  9 2020  4:27PM: The workflow has been recovered and has resumed execution from a previously persisted state.
------------------------------------------------------------
Jan 10 2020  2:02PM: The workflow has been recovered and has resumed execution from a previously persisted state.
------------------------------------------------------------

**Comment by NileshGhodekar** [comment]
What event log you are looking at? MIMWAL informational events will go to WAL event log.

**Comment by wiemerr** [comment]
I am expecting to see events like the following in the Forefront Identity Manager log.  This is from my QA where I have not applied SP2.  In DEV where I have updated to SP2 there are no events like this one.  The absence of these informational events makes debugging Workflows a real challenge.


WAL (2.19.0112.0): 01/10/2020 01:07:54.0132: Added the resource 'Queries/AccessRequests' and its attribute 'current_manager' to the read dictionary.
Extended Properties:
WorkflowInstanceId: ef186907-7cf8-4a30-a01e-e8dd1735d4d4
TargetId: faf88f68-ce9f-49e5-b856-c42e77078612
RequestId: 7d56a0b6-e932-4825-be4e-efe549a47255
WorkflowDefinitionId: 9e2d2916-f65d-44e2-9368-0e75456dafa9
ActorId: 7fb2b853-24f0-4498-9534-4e10589723c4

**Comment by wiemerr** [comment]
I see the Verbose events in the WAL log.  

So I have not described to problem correctly.  The thing that has changed with SP2 is that the Information events are not present in the Forefront Identity Manager log.

**Comment by wiemerr** [comment]
So what appears to have changed is this section of the config file where in pre-SP2 the logging is "ALL" whereas post SP2 this is only set to Warning.  I changed this to All in the SP2 environment and I once again see the MIMWAL Information events.

  <system.diagnostics>
    <switches>
      <add name="System.Workflow LogToTraceListeners" value="1" />
      <add name="System.Workflow.Runtime.Hosting" value="Verbose" />
      <add name="System.Workflow.Runtime" value="Verbose" />
      <add name="System.Workflow.Runtime.Tracking" value="Verbose" />
      <add name="System.Workflow.Activities" value="Verbose" />
      <add name="System.Workflow.Activities.Rules" value="Verbose" />
      <add name="AllSwitch" value="All" />
    </switches>

**Comment by wiemerr** [comment]
The paste seems to have failed
  <system.diagnostics>
    <switches>
      <add name="System.Workflow LogToTraceListeners" value="1" />
      <add name="System.Workflow.Runtime.Hosting" value="Verbose" />
      <add name="System.Workflow.Runtime" value="Verbose" />
      <add name="System.Workflow.Runtime.Tracking" value="Verbose" />
      <add name="System.Workflow.Activities" value="Verbose" />
      <add name="System.Workflow.Activities.Rules" value="Verbose" />
      <add name="AllSwitch" value="All" />
    </switches>

**Comment by wiemerr** [comment]
`  <system.diagnostics>
    <switches>
      <add name="System.Workflow LogToTraceListeners" value="1" />
      <add name="System.Workflow.Runtime.Hosting" value="Verbose" />
      <add name="System.Workflow.Runtime" value="Verbose" />
      <add name="System.Workflow.Runtime.Tracking" value="Verbose" />
      <add name="System.Workflow.Activities" value="Verbose" />
      <add name="System.Workflow.Activities.Rules" value="Verbose" />
      <add name="AllSwitch" value="All" />
    </switches>`

**Comment by NileshGhodekar** [comment]
closing this as you seems to have figured it out.

**Comment by wiemerr** [comment]
Thanks you - SP2 changed the defaults for logging which caused the MIMWAL Information events to be lost.  Changing the AllSwitch to All in the MIM service config file reverts to the pre-SP2 default.
