### ISSUE TITLE
MIMWAL Issue while getting data from remote SQL server

### ISSUE THREAD

**Issue by girirajbhamu** [microsoft/MIMWAL#83]
Hi Everyone,

I am using MIMWAL PowerShell Activity for one of my customer's requirement. On MIM Portal server I have tested on script in **Powershell IDE** by running as MIM Service account. Script runs just fine and giving expected output. Just FYIP: We have SQL user to connect with SQL server. While using it in Activity to make SQL connection, It is not bringing any data out of SQL. Below is the part of query not getting executed:

$dataSource = "X.X.X.X"
            $user = "Username"
            $pwd = "Password"
            $database = "Database Name"
            ﻿$connectionString="Server=$dataSource;uid=$user;pwd=$pwd;Database=$database;Integrated Security=False;"
            $connection = New-Object System.Data.SqlClient.SqlConnection
            $connection.ConnectionString = $connectionString
            $connection.Open()
            $command = $connection.CreateCommand()
            $query = $("SELECT * FROM [Table] where Filter")
           
            $command.CommandText = $query
            $SqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter
            $SqlAdapter.SelectCommand = $command
            $DataSet = New-Object System.Data.DataSet
            $SqlAdapter.Fill($DataSet)
            $connection.Close()
            $table=$DataSet.Tables[0]
            $All_Values=$table.ItemArray
            $Template_Value=$All_Values[16]
NOTE: No Output in $Template_Value. I have verified and $All_Value also nor bringing any data. I have also tried to create one table in MIM SQL server and MIM Service account has permission on that but still getting same error. 

Kindly help and suggest how to make SQL connectivity in MIMWAL PowerShell Activity. Thanks in Advance.

**Comment by bpalfaro** [comment]
I have had success using these functions to call a SQL Server query with returned data.  [https://github.com/Microsoft/MIMWAL/wiki/Data-Functions](https://github.com/Microsoft/MIMWAL/wiki/Data-Functions)

However, I would recommend using Integrated Security for your DB connection.  Setup the MIM Service account as a user on the database with limited query capability on the desired table.

Also, you are running as a batch job.  So, did you set any of these recommended security restrictions when setting up the MIM Service Account?  That may be another reason for your issue.

Use the following restrictions on the service accounts:
Deny logon as a batch job
Deny logon locally
Deny access to this computer from the network

[https://social.technet.microsoft.com/wiki/contents/articles/33214.fim-2010mim-2016-planning-security-setup-for-accounts-groups-and-services-part-4-detailed-description.aspx#FIM_Service_service_account](https://social.technet.microsoft.com/wiki/contents/articles/33214.fim-2010mim-2016-planning-security-setup-for-accounts-groups-and-services-part-4-detailed-description.aspx#FIM_Service_service_account)

**Comment by girirajbhamu** [comment]
With the help of information provided by "bpalfaro" , I have modified my script and was able to get it working.
