### ISSUE TITLE
From address cannot be configured

### ISSUE THREAD

**Issue by PeterNiles61** [microsoft/MIMWAL#84]
There is no option to configure the From address for "Send Email Notification". It is also not clear how  the current From address is generated.

**Comment by Amethi** [comment]
MIMWAL doesn't send the email. The MIM Service does. Whatever you have configured in your service configuration file and on the mailbox user itself will be what's used.

**Comment by PeterNiles61** [comment]
Many thanks Amethi. That was it. I guess I should have known...
