### ISSUE TITLE
"File not found" issue with Sign.cmd

### ISSUE THREAD

**Issue by joselgarza** [microsoft/MIMWAL#87]
Hi Nilesh,

"Sign.cmd" needs to be edited to remove the \ from some of the defined variables so that the file path built works when looking for the required dlls.  With the current build, we are seeing the path with double \ as: 

ERROR: File '"C:\MIM\MIMWAL\MIMWAL-2.20.0523.0\src\SolutionOutput**\\\\**MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll"' Not Found.

This can be resolved by just removing the '\' currently in the cmd file as they are unnecessary.  Just a heads up!  👍

**Comment by NileshGhodekar** [comment]
@joselgarza, this script is not changed for last 6 years and runs fine, so you might be attributing wrong reason for your initial failure.  The quotes are mandatory if you have spaces in for folder names. So what version of Windows you are not able to run to script?

**Comment by joselgarza** [comment]
The quotes are not the problem.  The issue is the variable "%~dp0\MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.dll".  I'm saying that, to make this work, I had to remove the slash between %~dp0 and Microsoft...  Note that the fourth variable doesn't have the slash, and that works fine.  I just had to change the first and second one.  By leaving the slash, the resulting path being checked for the dll has a double slash in the path, as the %~dp0 is also passing a slash at the end of the string.  This was my experience.

**Comment by NileshGhodekar** [comment]
Which version of Windows is causing issues with "\\"?  You can have as many slashes as you want and it would still work just fine :) Try "cd" on a cmd prompt with as many slashes as you want, so that will not be the reason for your initial failure. (agree on having consistency in the cmd file though as it can lead to red herring)

**Comment by joselgarza** [comment]
I'm running Windows Server 2019 DC.

**Comment by NileshGhodekar** [comment]
Have not tested the batch file but cd C:\\\\\\\\\\\\\\\Users works just fine.

**Comment by NileshGhodekar** [comment]
Closing this as a non-repro.
