### ISSUE TITLE
GenerateRandomPassword Function

### ISSUE THREAD

**Issue by dupward** [microsoft/MIMWAL#88]
Hi, I've noticed that the GenerateRandomPassword Function can be found via search, but is not included in any of the site menus etc.. This is a supported function correct?

thanks

**Comment by NileshGhodekar** [comment]
Hi @dupward, it's listed in the master lists in the wiki https://github.com/Microsoft/MIMWAL/wiki/Functions. But now I'll link it under Text functions sidebar as well. Thanks!

**Comment by NileshGhodekar** [comment]
Actually, the Markup is there in the Text function wiki, but for some strange reason the page is not rendering that row. Strange!

**Comment by NileshGhodekar** [comment]
Fixed now. Probably some non-printable char somewhere. A copy and paste fixed it.
