### ISSUE TITLE
How to monitor changes in Workflow

### ISSUE THREAD

**Issue by DuuuDik** [microsoft/MIMWAL#91]
Hello everyone! I am a total noobie to MIM and MIMWAL, so I need to ask for your assistance, fellas.

I need to check whether someone changed my workflows attributes. Basically, what I need is log of changes. Does something like that exits in MIM? What command do I need to see it? 

And whether it is possible to change "Created Time" attribute in Common attributes? I know, it is written that it cant be changed, but someone told me, that is not completely true.

Really looking forward to your replies

**Comment by bpalfaro** [comment]
You can use the Request lookup in MIMWAL workflows to see changes/deletes to attributes.  See here https://github.com/Microsoft/MIMWAL/wiki/Lookups#request

**Comment by NileshGhodekar** [comment]
Thanks @bpalfaro! @DuuuDik not sure if this was your first question and it it was answered.  As for the second one on "Created Time", there is nothing you cannot hack if you want to, but this will not be a forum to discuss unsupported methods.

**Comment by DuuuDik** [comment]
Thank you @bpalfaro, @NileshGhodekar for your answers!
