### ISSUE TITLE
Feature Request - CamelCase

### ISSUE THREAD

**Issue by braggaboutme** [microsoft/MIMWAL#94]
Can you please implement a function that will format last names of people that have a Camel Case last name?

Some examples of those names are:
DaSilva
DaCosta
MacCormack
MacKee
McCaskill
LeGrand

**Comment by NileshGhodekar** [comment]
This is a very hard problem to automate and almost impossible to get 100% right without human input. The easiest solution fo this is to make it a requirement for data entry or provide self-service to the end-users.

**Comment by Amethi** [comment]
Not to mention that there's nothing weirder than folk - some people will want to have their name in a specific, i.e. Some folk like their Dutch surnames names in `Vanderdude` and some like it in `Van der Dude` and some in `Van Der Dude`. Who are you to say what it should be? Better to let the issue be a source-data/human-entry issue and then provide self-service for end-users to correct it as @NileshGhodekar  says.

**Comment by Amethi** [comment]
Though if you wanted to take on the risk of getting it wrong/upsetting people then you could achieve this using the [RegexMatch ](https://github.com/Microsoft/MIMWAL/wiki/RegexMatch-Function) and [RegexReplace](https://github.com/Microsoft/MIMWAL/wiki/RegexReplace-Function) functions I'd have thought.

**Comment by braggaboutme** [comment]
OK, thanks for the feedback. I think I'll create a lookup table that can be queried with MIMWAL and update the attributes with RegexReplace.
