### ISSUE TITLE
DateTimeFromFileTimeUTC Function error (attribute Type)

### ISSUE THREAD

**Issue by juancarloscanto** [microsoft/MIMWAL#96]
I am try to use the DateTimeFromFileTimeUTC Function, just as indicated in the example: DateTimeFromFileTimeUTC([//Target/AccountExpires]) to conver AccountExpires from AD to MIM format (to configure notification MPR), but the workflow give this error:
Exception occurred while attempting to 'resolve' function 'System.ArgumentOutOfRangeException: Not a valid Win32 FileTime. Parameter name: fileTime at System.DateTime.FromFileTimeUtc(Int64 fileTime) at MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Common.ExpressionFunction.DateTimeFromFileTimeUtc() at MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Common.ExpressionFunction.Run()': 'DateTimeFromFileTimeUTC('9223372036854775807')'.
//Target/AccountName is an Integer Attribute and destination is a DateTime Attribute.

Am I doing something wrong?

I also need to convert pwdLastSet y LastLogonTimeStamp, could I use the same function?

Thanks in advance
Best Regards

**Comment by NileshGhodekar** [comment]
Try this in PowerShell [DateTime]::FromFileTimeUtc(9223372036854775807). It seems you have at least one digit too much. If you drop any one digit, you at least get some date back.

**Comment by juancarloscanto** [comment]
But the value is from AD (I import AccountExpires from AD, synchronize to MIM and try to conver in a MIM Workflow). How can I drop one digit for the data I read from AD?
I configure the workflow like this:
![image](https://user-images.githubusercontent.com/26442774/105854305-80db8c00-5fc5-11eb-8bc0-a0322366c892.png)

Let me know if you can see the picture
Thanks

**Comment by NileshGhodekar** [comment]
https://docs.microsoft.com/en-us/windows/win32/adschema/a-accountexpires will provide some clue :)

**Comment by juancarloscanto** [comment]
Ok. So, the problem is that this number is too big?
I use the advanced option to use small numbers:
![image](https://user-images.githubusercontent.com/26442774/105895002-b5663c80-5ff3-11eb-9260-4db2ea474357.png)

I use '441481644000000000' (this number represents December 31, 2999, after this day it will not be my problem :-) )

The conversion in the other (DateTimeToFileTimeUTC function) way support bigger numbers, for example, I configured a workflow like this:
![image](https://user-images.githubusercontent.com/26442774/105897286-bcdb1500-5ff6-11eb-9128-aed3d7d8aa11.png)

and a date like: '9999-12-31T00:00:00.000' is converted in: '2650466880000000000', (it is working now, in another Lab) but If I configure AccountExpires in AD with '9999-12-31'  (attribute has '2650466880000000000' value) DateTimeFromFileTimeUTC Function fails.

Regards

**Comment by NileshGhodekar** [comment]
Hi @juancarloscanto, I'll be closing this as the boundary you need to handle yourself - you can use IIF function appropriately if needed. You are also welcome to raise a bug with .NET Framework product support if you see different behaviours in different .NET functions.
