### ISSUE TITLE
Verify Request - Error Message

### ISSUE THREAD

**Issue by dupward** [microsoft/MIMWAL#97]
Hi, we are experiencing an issue with the Verify Request Activity.
Environment:
MIM: 4.6.359.0
MIMWAL: 2.19.112.0

We are validating that a manager is present when creating a new user in the MIM Portal. When submitting an invalid request, the Verify Request Activity works properly, but we're unable to read the error message, we just see a grey screen. Looking at the request, we can see the error message properly in the "Request Workflow Remarks" section - Manager is required.
![create-user-screen](https://user-images.githubusercontent.com/595428/106059363-9e415080-60c0-11eb-8545-b0e69a9c9148.png)

**Comment by NileshGhodekar** [comment]
@dupward, MIMWAL does not play any part in rendering UI. You need to investigate this as a MIM Portal issue.

**Comment by dupward** [comment]
Thank you.
